export const partners = [
  {
    id: "medispec",
    name: "Medispec",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/medispec.svg",
    website: "https://medispec.com/",
    invertColor: true,
    categories: ["urology"],
    products: ["Shockwave Therapy", "ED Treatment", "Lithotripsy"],
  },
  {
    id: "dornier-medtech",
    name: "Dornier MedTech",
    country: "Germany",
    flag: "🇩🇪",
    logo: "/partners/dornier-medtech.png",
    website: "https://www.dornier.com/",
    invertColor: false,
    categories: [""],
    products: ["Lithotripsy Systems", "ESWL Technology", "Stone Treatment"],
  },
  {
    id: "wikkon",
    name: "Wikkon",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/wikkon.png",
    website: "https://www.eswl.com/about-us/",
    invertColor: false,
    categories: [""],
    products: ["ESWL Systems", "Lithotripsy", "Urological Equipment"],
  },
  {
    id: "potent-medical",
    name: "Potent Medical",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/potent-medical.webp",
    website: "https://www.potent-medical.com/",
    invertColor: false,
    categories: ["urology"],
    subcategories: ["urology-equipment"],
    products: ["Holmium Lasers", "Thulium Fiber Lasers", "Surgical Lasers"],
  },
  {
    id: "redpine",
    name: "Redpine",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/redpine.png",
    website: "https://en.redpinemed.com/",
    invertColor: false,
    categories: ["urology"],
    products: ["Endoscopy", "Imaging Systems", "Urological Instruments"],
  },
  {
    id: "allwin",
    name: "Allwin",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/allwin.jpg",
    website: "https://allwinmedical.com/",
    invertColor: false,
    categories: ["urology"],
    subcategories: ["urology-consumables"],
    products: [
      "Ureteral Stents",
      "Renal Transplant Stents",
      "Medical Consumables",
    ],
  },
  {
    id: "boston-scientific",
    name: "Boston Scientific",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/boston-scientific.png",
    website:
      "https://www.bostonscientific.com/en-US/patients-caregivers/device-support/penile-implants.html",
    invertColor: false,
    categories: [""],
    products: ["Penile Implants", "Urological Devices", "Endourology"],
    tag: "Penile Implants",
  },
  {
    id: "combat-medical",
    name: "COMBAT Medical",
    country: "United Kingdom",
    flag: "🇬🇧",
    logo: "/partners/combat-medical.png",
    website: "https://combatcancer.com/",
    invertColor: false,
    categories: ["cancer-treatment"],
    products: ["Oncology Equipment", "Cancer Therapy Systems", "Radiotherapy"],
  },
  {
    id: "basda",
    name: "BASDA",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/basda.png",
    website: "https://www.basdamri.com/",
    invertColor: false,
    categories: ["medical-imaging"],
    products: ["MRI Systems", "CT Scanners", "X-Ray Equipment"],
  },
  {
    id: "excite-medical",
    name: "Excite Medical",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/excite.png",
    website: "https://excitemedical.com/",
    invertColor: true,
    categories: ["spinal-decompression"],
    products: [
      "Spinal Decompression Systems",
      "Therapy Equipment",
      "Treatment Solutions",
    ],
  },
  {
    id: "wego",
    name: "WEGO",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/WEGO.png",
    website: "https://www.wegomedical.com/",
    categories: ["orthopedics"],
    products: ["Orthopedic Treatment Solutions", "Diagnostic Equipment"],
  },
  {
    id: "enovis",
    name: "Enovis",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/enovis.png",
    website: "https://enovis.com/",
    categories: ["orthopedics"],
    products: [
      "Orthopedic Implants",
      "Surgical Instruments",
      "Treatment Solutions",
    ],
  },

  {
    id: "concemed",
    name: "ConceMed",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/concemed.png",
    website: "https://www.concemed.com/",
    invertColor: false,
    categories: ["endoscopy"],
    products: ["Endoscopy Systems", "Gastroscopes", "Colonoscopy"],
    tag: "Coming Soon",
  },
  {
    id: "adtec-premium-plasma",
    name: "Adtec Premium Plasma",
    country: "Japan",
    flag: "🇯🇵",
    logo: "https://adtechealthcare.com/wp-content/uploads/2025/09/AdTec_Horizontal-Full-colour-scaled.png",
    website: "https://adtechealthcare.com/",
    categories: ["wound-care"],
    products: ["Plasma Technology", "Medical Imaging Solutions"],
    tag: "Coming Soon",
  },
];

// Product categories for navigation
export const productCategories = [
  {
    id: "cancer-treatment",
    name: "Cancer Treatment",
    slug: "cancer-treatment",
    description: "Advanced oncology equipment and cancer therapy systems",
    icon: "Microscope",
  },
  {
    id: "urology",
    name: "Urology",
    slug: "urology",
    description: "Comprehensive urological treatment and diagnostic solutions",
    icon: "Stethoscope",
  },
  {
    id: "medical-imaging",
    name: "Medical Imaging",
    slug: "medical-imaging",
    description: "State-of-the-art diagnostic imaging systems",
    icon: "ScanLine",
  },
  {
    id: "endoscopy",
    name: "Endoscopy",
    slug: "endoscopy",
    description:
      "Advanced gastroscope and colonoscope systems for diagnostic and therapeutic procedures",
    icon: "Activity",
  },
  {
    id: "spinal-decompression",
    name: "Spinal Decompression",
    slug: "spinal-decompression",
    description: "Advanced spinal decompression therapy systems and equipment",
    icon: "Settings2",
  },
  {
    id: "wound-care",
    name: "Wound Care (Cold Plasma)",
    slug: "wound-care",
    description: "Innovative wound care and management solutions",
    icon: "Package",
  },
  {
    id: "orthopedics",
    name: "Orthopedics",
    slug: "orthopedics",
    description: "Comprehensive orthopedic treatment and diagnostic solutions",
    icon: "Activity",
  },
];

// Product subcategories linked to parent categories
export const productSubcategories = [
  // Urology subcategories
  {
    id: "urology-equipment",
    name: "Equipments",
    slug: "equipment",
    categoryId: "urology",
    description: "Advanced urological equipment and surgical systems",
    types: ["Lithotripsy", "Surgical Lasers", "Diagnostic Equipment"],
  },
  {
    id: "urology-consumables",
    name: "Consumables",
    slug: "consumables",
    categoryId: "urology",
    description: "Urological disposables and consumable products",
    types: ["Ureteral Stents", "Renal Transplant Stents", "Surgical Supplies"],
  },
  // Cancer Treatment subcategories
  {
    id: "cancer-treatment-systems",
    name: "Treatment Systems",
    slug: "treatment-systems",
    categoryId: "cancer-treatment",
    description: "Advanced cancer treatment and therapy systems",
    types: ["Bladder Cancer Treatment", "Chemotherapy Systems", "Radiotherapy"],
  },
  // Medical Imaging subcategories
  {
    id: "medical-imaging-systems",
    name: "Imaging Systems",
    slug: "imaging-systems",
    categoryId: "medical-imaging",
    description: "Diagnostic imaging and scanning systems",
    types: ["MRI Systems", "CT Scanners", "X-Ray Equipment"],
  },
  {
    id: "gastroscopy",
    name: "Gastroscopy",
    slug: "gastroscopy",
    categoryId: "endoscopy",
    description:
      "Gastroscopes and colonoscopes for gastrointestinal procedures",
    types: [
      "Video Gastroscopes",
      "Colonoscopy Systems",
      "Endoscopy Accessories",
    ],
  },
  {
    id: "colonoscopy",
    name: "Colonoscopy",
    slug: "colonoscopy",
    categoryId: "endoscopy",
    description:
      "Colonoscopy systems and accessories for colorectal procedures",
    types: [
      "Video Colonoscopes",
      "Colonoscopy Systems",
      "Endoscopy Accessories",
    ],
  },
  {
    id: "endoscopy-imaging-systems",
    name: "Imaging Systems",
    slug: "imaging-systems",
    categoryId: "endoscopy",
    description:
      "Video processors and imaging systems for endoscopic procedures",
    types: [
      "Video Processors",
      "Image Processing Systems",
      "LED Light Sources",
    ],
  },
  {
    id: "infection-management",
    name: "Infection Management",
    slug: "infection-management",
    categoryId: "wound-care",
    description: "Infection control and management solutions",
    types: ["Antimicrobial Dressings", "Wound Cleansing Products"],
  },
  {
    id: "trauma",
    name: "Trauma",
    slug: "trauma",
    categoryId: "orthopedics",
    description: "Trauma care and management solutions",
    types: ["Fracture Fixation", "Trauma Implants", "Surgical Instruments"],
  },
  {
    id:"foot-and-ankle",
    name: "Foot & Ankle",
    slug: "foot-and-ankle",
    categoryId: "orthopedics",
    description: "Foot and ankle care and management solutions",
    types: ["Foot & Ankle Implants", "Surgical Instruments", "Treatment Solutions"],
  }
];

// Company stats

// Company features
export const companyFeatures = [
  {
    icon: "Award",
    title: "ISO Certified Operations",
    description:
      "Maintaining international quality standards in all our processes and services.",
  },
  {
    icon: "Shield",
    title: "SFDA Approved Products",
    description:
      "All our medical equipment meets Saudi FDA regulatory requirements.",
  },
  {
    icon: "Headphones",
    title: "Comprehensive Support",
    description:
      "From installation to maintenance, our team provides complete technical support.",
  },
  {
    icon: "TrendingUp",
    title: "Continuous Innovation",
    description:
      "Staying ahead with the latest medical technologies and healthcare solutions.",
  },
];

// Company values (Vision, Mission, Values)
export const companyValues = [
  {
    icon: "Eye",
    title: "Our Vision",
    description:
      "Keep pace with fast-moving technology for Saudi Arabia's 2030 vision to accomplish excellence in healthy living by offering complete medical solutions.",
    gradient: "from-primary/10 to-primary/5",
    iconColor: "text-primary",
  },
  {
    icon: "Target",
    title: "Our Mission",
    description:
      "Inspire hope and improve quality of life by offering verifiable, effective professional solutions ensuring partner satisfaction.",
    gradient: "from-accent/10 to-accent/5",
    iconColor: "text-accent",
  },
  {
    icon: "Heart",
    title: "Our Values",
    description:
      "Trust, loyalty, and respect — the constant fundamentals of our commitment to excellence in healthcare partnerships.",
    gradient: "from-gold/10 to-gold/5",
    iconColor: "text-gold",
  },
];

export const products = [
  // Medispec Products
  {
    id: "medispec-em1000-eswl",
    name: "EM1000™ ESWL System",
    brand: "Medispec",
    partnerId: "medispec",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Lithotripsy",
    is_parent_product: false,
    images: [
      "/medicspec.png",
      "https://www.medispec.com/wp-content/uploads/2022/08/EM1000-36-Custom.png",
      "https://www.medispec.com/wp-content/uploads/2021/08/EM1000-Title-pic-e1638881167440.png",
      "https://www.medispec.com/wp-content/uploads/2021/10/stones.png",
    ],
    description:
      "The EM1000™ ESWL System is an advanced electromagnetic lithotripter designed for non-invasive stone management treatment with a high stone-free rate, low re-treatment rate, and outstanding clinical results. Its modular and mobile design fits a wide range of clinical environments without the need for special infrastructure. It offers real-time stone visualization and integrated imaging options.",
    features: [
      "Electromagnetic shockwave technology for efficient stone fragmentation",
      "Highest stone-free rate and lowest re-treatment rate in its class",
      "Modular, mobile design suitable for a variety of clinical settings",
      "Real-time stone visualization during treatment",
      "Versatility for both lithotripsy and endo-urology procedures",
      "Integrated X-ray and ultrasound imaging options",
    ],
    technical_specifications: {
      technology: "Electromagnetic shockwave generation",
      treatment_modes: ["Lithotripsy", "Endo-urology procedures"],
      mobility: "Modular and mobile system",
      integration: "X-ray and optional ultrasound imaging",
      clinical_benefits: [
        "High stone-free rate",
        "Low re-treatment rate",
        "Reduced treatment time",
        "Fits in small clinics to large hospitals",
      ],
    },
    accessories_included: [
      "Control console with automatic stone localization",
      "Motorized treatment table interface",
      "Integrated imaging (Visionspec™) compatibility",
      "Detachable ultrasound probe support",
    ],
    applications: [
      "Renal stone treatment",
      "Ureteric stone treatment",
      "Endo-urology procedures",
    ],
    certifications: [],
    regulatory: {
      fda_classification:
        "Class II – Extracorporeal Shock Wave Lithotripter (21 CFR 876.5990)",
      intended_use:
        "Non-invasive fragmentation of urinary tract stones including kidney and ureter stones",
    },
    distributor: {
      name: "",
      region: "",
      contact: "",
    },
  },
  // Potent Medical Products
  {
    id: "potent-high-power-holmium-laser-system-hp-160w-cannon",
    name: "High Power Holmium Laser System (HP 160W) – Cannon™ Double Pulse Technology",
    brand: "Potent Medical",
    partnerId: "potent-medical",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Surgical Lasers",
    is_parent_product: false,
    images: [
      "https://www.potent-medical.com/wp-content/uploads/2024/06/Holmium-Laser-HP.png",
    ],
    description:
      "The High Power Holmium Laser System (HP 160W) by Potent Medical is a high-performance Ho:YAG laser platform powered by Cannon™ Double Pulse Technology, designed to deliver faster lithotripsy procedures and improved outcomes in BPH (HoLEP) treatment. It provides high working frequency up to 120Hz, ultra-long pulse width up to 2500μs for dusting, and enhanced precision through configurable pulse width and energy control. The system is built to improve efficiency, reduce retropulsion, shorten learning curves, and support smoother workflow with a user-friendly touchscreen, fiber auto-detection, double footswitch, and effortless mobility.",
    features: [
      "Cannon™ Double Pulse Technology for superior energy transmission",
      "Ultra-long pulse width up to 2500μs for dusting and fine stone fragmentation",
      "Ultra-high working frequency up to 120Hz using pulse splitting technology",
      "Configurable pulse width and energy with continuous dual-pulse output (Pulse Guidance™)",
      "More efficient fragmentation and faster lithotripsy procedure time",
      "Faster and finer dusting with excellent stone-free rate",
      "Less retropulsion for improved control and stable targeting",
      "For BPH (HoLEP): faster enucleation and faster hemostasis",
      "For BPH (HoLEP): same-day discharge and catheter-free outcomes",
      "For BPH (HoLEP): improved laser-tissue interaction for deeper vaporization and more effective incisions",
      "For BPH (HoLEP): effective coagulation of small blood vessels up to 2mm supporting precise, bloodless incisions",
      "For Lithotripsy: reduced stone migration risk and reduced ureteral tissue damage",
      "User-friendly rotatable and tiltable touchscreen",
      "Intuitive UI with intelligent preset modes (cutting, hemostasis, dusting, fragmenting, popcorn)",
      "Automatic detection of laser fiber diameter",
      "Protective dust cover on fiber connector to prevent dust ingress and ensure accurate output power",
      "Double footswitch for rapid switching between treatment modes",
      "Integrated casters for effortless mobility between operating rooms",
      "APFC efficiency boost enabling operation with a smaller power supply",
    ],
    technical_specifications: {
      max_power_watts: 160,
      max_frequency_hz: 120,
      pulse_width_max_us: 2500,
      technology: [
        "Cannon™ Double Pulse Technology",
        "Pulse splitting technology",
        "Pulse Guidance™",
      ],
      preset_modes: [
        "cutting",
        "hemostasis",
        "dusting",
        "fragmenting",
        "popcorn",
      ],
      workflow_features: [
        "Automatic laser fiber diameter detection",
        "Rotatable & tiltable touchscreen",
        "Double footswitch mode switching",
        "Mobility casters",
        "APFC energy efficiency",
      ],
    },
    applications: [
      "Lithotripsy (stone fragmentation / dusting)",
      "RIRS (Retrograde Intrarenal Surgery) including large-volume kidney stones and kidney-cast stones",
      "HoLEP (Holmium Laser Enucleation of the Prostate) for BPH treatment",
      "Percutaneous large-caliber bladder stones",
      "Percutaneous large-caliber kidney stones",
    ],
    advantages_for_surgeon: [
      "Shorter procedure times",
      "More efficient stone fragmentation",
      "Faster and finer dusting performance",
      "Reduced retropulsion for improved control",
      "Faster enucleation and stronger hemostasis during HoLEP",
      "Improved visibility and easier plane localisation during HoLEP",
      "Shortened learning curve for beginners",
    ],
    benefits_for_patient: [
      "Same-day discharge for BPH treatment",
      "Near bloodless HoLEP with improved safety profile",
      "Reduced operative time and improved recovery experience",
    ],
    additional_info: {
      source_url:
        "https://www.potent-medical.com/product/high-power-holmium-laser-system/",
      contact_phone: "+86-13828248946",
      contact_email: "marketing@potent-medical.com",
      company_email: "info@potent-medical.com",
      company_location:
        "Guangzhou City, China Room 5003, Bldg. A01, Ping’an Technology Guigu Industrial Park, No. 74 Chuangyu Road, Ningxi Street, Zengcheng District",
    },
  },
  {
    id: "potent-thulium-fiber-laser-pulsed-master",
    name: "Thulium Fiber Laser (Pulsed Master)",
    brand: "Potent Medical",
    partnerId: "potent-medical",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Surgical Lasers",
    is_parent_product: false,
    images: [
      "https://www.potent-medical.com/wp-content/uploads/2024/10/Thulium-Fiber-Laser.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/03/%E5%AE%B9%E5%99%A8-1@1x-2025-03-31T154907.639-1.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/04/TURP.gif",
    ],
    description:
      "The Potent Thulium Fiber Laser (Pulsed Master) is a next-generation urology laser system designed to deliver unparalleled precision, speed, and safety for stone management (RIRS) and BPH treatment (ThuFLEP). Operating at a 1940nm wavelength with high water absorption, it concentrates energy within <0.3mm depth to enable efficient stone dusting, smooth tissue dissection, and strong hemostasis while reducing retropulsion and improving surgical control.",
    features: [
      "1940nm wavelength with high water absorption (120 cm⁻¹, 4.8× Ho:YAG) concentrating energy within <0.3mm depth for efficient stone and BPH treatment",
      "Enables precise dusting in stone surgery",
      "Supports smooth, continuous dissection in BPH treatment",
      "Less retropulsion for improved control and stability during ureteral stone treatment",
      "Superior dusting efficiency with finer stone fragmentation",
      "Reduced dependence on ureteral access sheath due to use of thin optical fibers",
      "Ease of access to challenging calyces using 50–150μm ultra-fine optical fiber (lower pole renal access)",
      "Shorter learning curve and improved usability for beginners due to better field of view and lower backlash",
      "Safe and efficient ThuFLEP system for BPH treatment",
      "97% hemostasis efficiency (claimed)",
      "Gentle yet effective ablation (claimed)",
      "0.2–0.5mm thermal penetration (claimed)",
      "28% faster recovery vs standard TURP (claimed)",
      "Low maintenance & operating costs with air cooling, 10,000+ hour diodes, and no fragile optics",
      "Compact design with minimal OR footprint",
      "Energy efficient with up to 12% laser conversion efficiency and low total power consumption (800–1,000W), nearly 10× lower than traditional Ho:YAG systems (claimed)",
      "Low noise operation compared to conventional water-cooled lasers",
      "Compatible with 110V–220V (10A/16A) for flexible installation",
      "Dual pedal foot switch for fast switching between 'Dusting' and 'Fragmentation'",
    ],
    technical_specifications: {
      wavelength_nm: 1940,
      water_absorption_cm_inverse: 120,
      water_absorption_vs_hoyag: "4.8× Ho:YAG",
      energy_penetration_depth_mm: "<0.3",
      thermal_penetration_mm: "0.2–0.5",
      laser_conversion_efficiency_percent: "up to 12%",
      total_power_consumption_watts: "800–1,000",
      cooling_system: "Air cooling",
      fiber_sizes_microns: ["50μm", "150μm"],
      voltage_compatibility: "110V–220V",
      power_current_support: "10A/16A",
      footswitch_modes: ["Dusting", "Fragmentation"],
    },
    applications: [
      "RIRS (Retrograde Intrarenal Surgery) stone management",
      "Laser lithotripsy with dusting and fragmentation",
      "Ureteral stone treatment with reduced retropulsion",
      "BPH treatment with ThuFLEP (Thulium Fiber Laser Enucleation of the Prostate)",
    ],
    advantages_for_surgeon: [
      "Higher efficiency and shorter intraoperative laser time due to high frequency and optimized pulse characteristics",
      "Improved targeting control from lower peak pulse value and longer pulse duration",
      "Better access to lower pole calyces using ultra-fine fibers",
      "More user-friendly workflow supporting faster learning curve for beginners",
      "Fast switching between dusting and fragmentation via dual pedal foot switch",
    ],
    benefits_for_patient: [
      "Potentially faster recovery compared to standard TURP (claimed)",
      "Lower thermal penetration supports controlled tissue effect (claimed)",
      "Improved treatment precision and safety profile (claimed)",
    ],
    additional_info: {
      source_url: "https://www.potent-medical.com/product/thulium-fiber-laser/",
      contact_phone: "+86-13828248946",
      contact_email: "marketing@potent-medical.com",
      company_email: "info@potent-medical.com",
      company_location:
        "Guangzhou City, China Room 5003, Bldg. A01, Ping’an Technology Guigu Industrial Park, No. 74 Chuangyu Road, Ningxi Street, Zengcheng District",
    },
  },
  {
    id: "potent-desktop-portable-xp-holmium-laser",
    name: "Desktop Portable XP Holmium Laser",
    brand: "Potent Medical",
    partnerId: "potent-medical",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Surgical Lasers",
    is_parent_product: false,
    images: [
      "https://www.potent-medical.com/wp-content/uploads/2024/05/Holmium-Laser-XP.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/02/2@1x-11.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/02/1@1x-85.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/02/1@1x-75.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/02/1@1x-77.webp",
      "https://www.potent-medical.com/wp-content/uploads/2025/02/1@1x-78.webp",
    ],
    description:
      "The Desktop Portable XP Holmium Laser is a compact, lightweight holmium laser system designed as a stone management expert, enabling surgeons to confidently treat stones of any size, type, or location—even in challenging and unpredictable cases. With a wide range of settings and five pulse width levels, it supports both tough-stone fragmentation using short pulses and efficient ablation/dusting using long pulses. The XP Series delivers portability, versatility, and consistent reliability across multiple hospital and clinical settings.",
    features: [
      "Stone management expert for treating stones of any size, type, or location",
      "Supports challenging and hard-to-predict stone cases",
      "Five pulse width levels for optimal performance across stone types",
      "Short pulses for tough stone fragmentation",
      "Long pulses for efficient ablation and dusting",
      "Wide range of settings to support different surgical needs",
      "40W power output designed for portability and versatility",
      "Lightweight and compact design built for effortless transport",
      "Designed for consistent reliability across multiple hospital settings",
      "Born for excellence with superior fragmentation and dusting efficiency",
    ],
    technical_specifications: {
      series: "XP Series",
      max_power_watts: 40,
      pulse_width_levels: 5,
      use_case_focus: ["Fragmentation", "Dusting", "Ablation"],
      portability: "Desktop / Portable",
    },
    applications: [
      "Urology stone management procedures",
      "Lithotripsy (fragmentation and dusting)",
      "Multi-setting use across hospitals and surgical centres",
    ],
    additional_info: {
      source_url:
        "https://www.potent-medical.com/product/desktop-portable-xp-holmium-laser/",
    },
  },
  {
    id: "potent-hz-series-holmium-laser",
    name: "Holmium Laser System HZ Series",
    brand: "Potent Medical",
    partnerId: "potent-medical",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Surgical Lasers",
    is_parent_product: true,
    images: [
      "https://www.potent-medical.com/wp-content/uploads/2024/01/123-2.png",
      "https://www.potent-medical.com/wp-content/uploads/2024/01/20240605172933.gif",
    ],
    description:
      "The Holmium Laser System HZ Series by Potent Medical is a versatile 90W holmium laser platform designed for stone and BPH treatment. Operating at 2100nm for efficient water absorption with reduced penetration, it provides flexible surgical treatment solutions with adjustable frequency, energy, and laser pulse duration. The system is built for quick workflow control through an intuitive touchscreen, supports a wide range of fiber sizes, and offers high mobility for diverse surgical and mobile settings.",
    features: [
      "Versatile 90W holmium laser system ideal for stone and BPH treatment",
      "2100nm wavelength with efficient water absorption and reduced penetration",
      "Flexible surgical treatment solutions with adjustable frequency and energy",
      "Adjustable laser pulse duration",
      "One platform designed for multiple surgical possibilities",
      "Intuitive touchscreen allows for quick parameter adjustments during surgery",
      "Fiber connector supports laser fibers from 200µm to 1000µm for various surgeries, including hard-to-reach cases",
      "Inbuilt powerful cooling system ensures optimal performance even in environments up to 30°C",
      "User-friendly and lower noise operation (half the noise of conventional holmium lasers)",
      "High mobility: moves smoothly across uneven surfaces, suitable for diverse surgical and mobile settings",
      "Compatible with Potent fiber solutions (150µm to 1000µm available)",
    ],
    technical_specifications: {
      max_power_watts: 90,
      wavelength_nm: 2100,
      fiber_connector_supported_range_microns: "200µm–1000µm",
      available_fiber_sizes_microns: "150µm–1000µm",
      cooling_system: "Inbuilt powerful cooling system",
      operating_environment_max_temp_c: 30,
      noise_level: "Half the noise of conventional holmium lasers",
      adjustability: ["Frequency", "Energy", "Laser Pulse Duration"],
    },
    applications: [
      "Laser lithotripsy",
      "Benign Prostatic Hyperplasia (BPH) treatment",
      "Soft tissue procedures",
      "Beyond urology applications (soft tissue use cases)",
    ],
    additional_info: {
      source_url:
        "https://www.potent-medical.com/product/holmium-laser-hz-series/",
      contact_phone: "+86-13828248946",
      contact_email: "marketing@potent-medical.com",
      company_email: "info@potent-medical.com",
    },
  },
  // Combat Medical Products
  {
    id: "combat-brs-hivec-bladder-cancer-system",
    name: "COMBAT BRS HIVEC® Bladder Cancer System",
    brand: "COMBAT Medical",
    partnerId: "combat-medical",
    category: "cancer-treatment",
    sub_category: "cancer-treatment-systems",
    product_type: "Bladder Cancer Treatment",
    is_parent_product: false,
    images: ["http://combatcancer.com/wp-content/uploads/2021/05/BRS_V5_C.jpg"],
    description:
      "The COMBAT BRS HIVEC® Bladder Cancer System is an advanced conductive bladder recirculation platform designed to deliver Hyperthermic Intra-VEsical Chemotherapy (HIVEC®) for patients with non-muscle invasive bladder cancer (NMIBC). It precisely controls intravesical chemotherapy temperature and circulation to enhance drug efficacy, improve homogeneous heat distribution, and optimise clinical outcomes.",
    features: [
      "Closed conductive recirculation system for consistent drug and heat distribution",
      "Accurate temperature control within ±0.2°C of set target",
      "Touchscreen user interface with real-time monitoring of temperature and pressure",
      "Built-in safety alarms for high/low temperature and pressure",
      "Patented aluminium heat exchanger for efficient heat transfer",
      "Peristaltic pump for smooth, continuous, reversible recirculation",
      "Flexible 16F 3-way catheter with coude tip for patient comfort",
    ],
    technical_specifications: {
      temperature_control_range_celsius: "41–44 °C",
      temperature_stability: "±0.2°C",
      catheter_size_fr: "16F 3-way",
      pressure_monitoring: "Continuous with automated safety cutoff",
      monitoring_interface: "Touchscreen with graphical readout",
      recirculation_system: "Peristaltic pump with bubble trap chamber",
      data_export: "USB (CSV/TXT formats)",
    },
    applications: [
      "Hyperthermic intravesical chemotherapy (HIVEC®) for NMIBC patients",
      "Alternative treatment for patients unfit for, intolerant of, or refusing BCG therapy",
      "Adjunct therapy post-TURBT in bladder cancer management",
    ],
    clinical_benefits: [
      "Promotes homogeneous heated chemotherapy delivery throughout the bladder",
      "Potential to improve drug efficacy compared with cold chemotherapy alone",
      "System designed for patient comfort at low pressure and flow rates",
      "Promising safety and tolerability profile in interim clinical data",
    ],
    certifications: [
      "IEC/UL 60601-1",
      "IEC 60601-1-2",
      "EN 55011",
      "CAN/CSA-C22.2",
      "CE Mark",
    ],
    references: [
      "HIVEC® stands for Hyperthermic Intra-VEsical Chemotherapy and is used as a bladder-sparing treatment option in intermediate and high-risk NMIBC patients, where BCG is intolerable or unavailable. :contentReference[oaicite:1]{index=1}",
      "The COMBAT BRS device uses a patented aluminium heat exchanger to deliver accurate and uniform heated chemotherapy distribution. :contentReference[oaicite:2]{index=2}",
      "Clinical data suggest a favorable patient tolerability and comparable side-effect profile to standard intravesical therapies. :contentReference[oaicite:3]{index=3}",
    ],
    distributor: {
      name: "Global Combat Medical Network",
      website: "https://combatcancer.com",
    },
  },
  // BASDA Products
  {
    id: "basda-bti-050-0-5t-permanent-magnet-mri",
    name: "BTI-050 0.5T Wide Open C-Shape Permanent Magnet MRI Machine",
    brand: "BASDA",
    partnerId: "basda",
    category: "medical-imaging",
    sub_category: "medical-imaging-systems",
    product_type: "MRI Systems",
    is_parent_product: false,
    images: [
      "https://www.basdamri.com/photo/ps32394899-wide_open_c_shape_0_5_tesla_permanent_magnet_mri_machine_bti_050.jpg",
    ],
    description:
      "The BASDA BTI-050 is a 0.5 Tesla wide open C-shape permanent magnet MRI system designed to deliver comfortable patient accessibility with reliable diagnostic imaging performance. Its open magnet design supports easier positioning, improved patient comfort, and broad clinical usability for routine imaging applications.",
    features: [
      "0.5 Tesla permanent magnet MRI system",
      "Wide open C-shape design for improved patient comfort and accessibility",
      "Designed for stable and consistent imaging performance",
      "Suitable for routine diagnostic imaging applications",
      "Optimised workflow for hospitals and imaging centres",
    ],
    technical_specifications: {
      magnetic_field_tesla: 0.5,
      magnet_type: "Permanent Magnet",
      magnet_structure: "Wide Open C-Shape",
      patient_access: "Open design for improved positioning",
      clinical_use: "Routine diagnostic MRI imaging",
    },
    system_components: [
      "Permanent magnet system",
      "RF system",
      "Gradient system",
      "Patient table",
      "Computer workstation",
      "MRI control software",
    ],
    applications: [
      "Routine diagnostic MRI imaging",
      "Musculoskeletal imaging",
      "Brain and neurological imaging",
      "Abdominal imaging",
    ],
    certifications: [],
    additional_info: {
      place_of_origin: "China",
      minimum_order_quantity: "1 set",
      delivery_time_days: "30-45 Days",
    },
  },
  {
    id: "basda-bstar-150f-1-5t-no-helium-superconducting-mri",
    name: "Bstar-150F 1.5T No-Helium Superconducting MRI Scanner",
    brand: "BASDA",
    partnerId: "basda",
    category: "medical-imaging",
    sub_category: "medical-imaging-systems",
    product_type: "MRI Systems",
    is_parent_product: false,
    images: [
      "https://www.basdamri.com/photo/ps33865573-1_5_tesla_no_helium_superconducting_mri_scanner_open_superconductive_mri_bstar_150f.jpg",
    ],
    description:
      "The BASDA Bstar-150F is a 1.5 Tesla superconducting MRI scanner engineered without the need for liquid helium, significantly reducing operational constraints and dependency on helium supply. It provides high magnetic field stability and excellent imaging performance with an active shielding design suitable for advanced clinical diagnostics. ",
    features: [
      "Helium-free superconducting magnet eliminates the need for liquid helium consumption. :contentReference[oaicite:1]{index=1}",
      "1.5 Tesla magnetic field for high-resolution diagnostic imaging. :contentReference[oaicite:2]{index=2}",
      "Active shielding method and modular design for easier installation and reduced footprint. :contentReference[oaicite:3]{index=3}",
      "Automatic field drop and restoration in power interruptions. :contentReference[oaicite:4]{index=4}",
      "Supports cloud interconnection for remote monitoring and control. :contentReference[oaicite:5]{index=5}",
    ],
    technical_specifications: {
      magnetic_field_tesla: 1.5,
      liquid_helium_liters: 0,
      magnet_type: "Superconductive (niobium-titanium alloys)",
      shielding_method: "Active",
      shimming_method: "Active + Passive + Dynamic",
      homogeneity_ppm: "≤0.01 (10 cm DSV)",
      field_stability_ppm_per_h: "≤0.1",
      inner_diameter_mm: 600,
      "5_gauss_fringe_field_m": "≤2.5 x 2.5 x 4.0",
      power_consumption_kw: "45",
    },
    system_components: [
      "No-helium superconducting magnet",
      "RF sub system with 8/16 channel receiver",
      "Gradient sub system with self-shielding coils",
      "Motor-driven patient table",
      "Water chiller cooling system",
      "Intelligent monitoring and control software",
    ],
    applications: [
      "Body and neurological diagnostic MRI",
      "Abdominal imaging",
      "Musculoskeletal imaging",
      "Cardiovascular MRI",
    ],
    certifications: ["ISO13485"],
    additional_info: {
      place_of_origin: "China",
      minimum_order_quantity: "1 set",
      delivery_time_days: "30-45 Days",
    },
  },
  {
    id: "basda-bstar-050-0-5t-dual-post-superconducting-open-mri",
    name: "Dual Post Superconducting 0.5 Tesla Open MRI Machine Bstar-050",
    brand: "BASDA",
    partnerId: "basda",
    category: "medical-imaging",
    sub_category: "medical-imaging-systems",
    product_type: "MRI Systems",
    is_parent_product: false,
    images: [
      "https://www.basdamri.com/photo/ps32748164-dual_post_superconducting_0_5_tesla_open_mri_machine_bstar_050.jpg",
    ],
    description:
      "The BASDA Bstar-050 is a dual post superconducting 0.5 Tesla open MRI system launched in 2016. It is designed to provide a low-cost, low-power-consumption open MRI solution with faster scanning speed than permanent magnet MRI and image quality close to 1.5T superconductive MRI, while reducing patient claustrophobia through its open magnet design.",
    features: [
      "0.5 Tesla superconductive open MRI scanner with dual post magnet design",
      "Low electricity cost compared to conventional 1.5T MRI systems",
      "Configured with Sumitomo 4K cold head to provide zero consumption of liquid helium",
      "Faster scanning time than permanent magnet MRI systems",
      "Image quality better than permanent magnet MRI and close to 1.5T superconductive MRI level",
      "Open magnet design reduces claustrophobic fear and patient involuntary movement artifacts",
      "Self-shielding gradient coil with high duty cycle gradient amplifier system",
      "Eddy zero technology and software algorithm to eliminate eddy current effects",
      "Special hardware noise reduction design reducing gradient noise up to 66%",
      "Air cooling gradient system to reduce maintenance cost",
      "4-channel RF receiving combined with parallel sampling and DDC digital direct sampling",
      "Supports advanced sequences including MRA, MRU/MRCP/MRM, and DWI imaging",
      "E-alarm real-time monitoring for magnet pressure, temperature, and liquid helium level with phone alerts",
    ],
    technical_specifications: {
      magnetic_field_tesla: 0.5,
      magnet_shape: "Dual Post",
      magnet_type: "Superconductive Magnet",
      vertical_gap_cm: 42,
      cooling: "Water-cooled helium",
      rf_channels: 4,
      gradient_cooling: "Air cooling",
      liquid_helium_consumption: "Zero (with 4K cold head)",
    },
    system_components: [
      "Dual post superconductive open magnet system",
      "Self-shielding gradient coil system",
      "High duty cycle gradient amplifier system",
      "4-channel RF receiving subsystem",
      "Parallel acquisition and DDC digital direct sampling technology",
      "Noise reduction hardware design for gradient system",
      "Interactive scan system with full-body scan kit and sequences",
      "E-alarm monitoring system (pressure, temperature, helium level)",
    ],
    applications: [
      "Routine full-body MRI scanning",
      "MR Angiography (MRA)",
      "MR Urography (MRU)",
      "MR Cholangiopancreatography (MRCP)",
      "MR Mammography (MRM)",
      "Diffusion Weighted Imaging (DWI)",
    ],
    certifications: ["CE", "ISO13485"],
    additional_info: {
      place_of_origin: "Guangdong, P.R.C.",
      model_number: "Bstar-050",
      minimum_order_quantity: "1 set",
      price: "Negotiable",
      packaging_details: "1 unit/wooden box",
      delivery_time_days: "30-45 Days",
      payment_terms: [
        "Credit card",
        "Paypal",
        "T/T",
        "Western Union",
        "MoneyGram",
      ],
      supply_ability: "200 machines per year",
    },
  },
  // Allwin Medical Devices Products
  {
    id: "Allsoft-ureteral-stents-open-closed-intraoperative",
    name: "allSoft Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
    brand: "Allwin Medical Devices",
    partnerId: "allwin",
    category: "urology",
    sub_category: "urology-consumables",
    product_type: "Ureteral Stents",
    is_parent_product: false,
    images: [
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Open-Tip-13.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Open-Tip-14-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Closed-Tip-13-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Closed-Tip-12-600x600.jpg",
    ],
    description:
      "The AllSoft Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopacity for accurate positioning, and centimeter markings for precise placement.",
    features: [
      "Low encrustation tendency to facilitate easy removal of the stent",
      "Soft polyurethane material ensures high patient comfort",
      "Wide lumen for superior drainage",
      "Radiopaque stent to enable accurate positioning",
      "Centimeter marking to aid in stent advancement and precise placement",
    ],
    variants: [
      "SOT4.7/16 | SS4.7/16 | SSI4.7/16",
      "SOT4.7/24 | SS4.7/24 | SSI4.7/24",
      "SOT4.7/26 | SS4.7/26 | SSI4.7/26",
      "SOT4.7/28 | SS4.7/28 | SSI4.7/28",
      "SOT4.7/30 | SS4.7/30 | SSI4.7/30",
      "SOT5/16 | SS5/16 | SSI5/16",
      "SOT5/24 | SS5/24 | SSI5/24",
      "SOT5/26 | SS5/26 | SSI5/26",
      "SOT5/28 | SS5/28 | SSI5/28",
      "SOT5/30 | SS5/30 | SSI5/30",
      "SOT6/16 | SS6/16 | SSI6/16",
      "SOT6/24 | SS6/24 | SSI6/24",
      "SOT6/26 | SS6/26 | SSI6/26",
      "SOT6/28 | SS6/28 | SSI6/28",
      "SOT6/30 | SS6/30 | SSI6/30",
      "SOT7/16 | SS7/16 | SSI7/16",
      "SOT7/24 | SS7/24 | SSI7/24",
      "SOT7/26 | SS7/26 | SSI7/26",
      "SOT7/28 | SS7/28 | SSI7/28",
      "SOT7/30 | SS7/30 | SSI7/30",
    ],
    combinations: {
      with_guidewire: "Add suffix - G",
      with_suture: "Add suffix - S",
      with_clamp: "Add suffix - C",
      with_hydrophilic_coating: "Add suffix - H",
    },
  },
  {
    id: "r-plus-ureteral-stents-open-closed-intraoperative",
    name: "R+ Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
    brand: "Allwin Medical Devices",
    partnerId: "allwin",
    category: "urology",
    sub_category: "urology-consumables",
    product_type: "Ureteral Stents",
    is_parent_product: false,
    images: [
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-16.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-16.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-17.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-14-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-13-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/R-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
    ],
    description:
      "The R+ Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopaque stent for accurate positioning, centre marking for precise placement, and a long pusher for use via ureteroscope.",
    features: [
      "Low encrustation tendency to facilitate easy removal of the stent",
      "Soft polyurethane material ensures high patient comfort",
      "Wide lumen for superior drainage",
      "Radiopaque stent to enable accurate positioning",
      "Centimetre marking to aid in stent advancement and precise placement",
      "4.7 Fr stent with a long pusher for ureteroscope use",
    ],
    variants: [
      "SOT4.7/16-R+ | SS4.7/16-R+ | SSI4.7/16-R+",
      "SOT4.7/24-R+ | SS4.7/24-R+ | SSI4.7/24-R+",
      "SOT4.7/26-R+ | SS4.7/26-R+ | SSI4.7/26-R+",
      "SOT4.7/28-R+ | SS4.7/28-R+ | SSI4.7/28-R+",
      "SOT4.7/30-R+ | SS4.7/30-R+ | SSI4.7/30-R+",
      "SOT5/16-R+ | SS5/16-R+ | SSI5/16-R+",
      "SOT5/24-R+ | SS5/24-R+ | SSI5/24-R+",
      "SOT5/26-R+ | SS5/26-R+ | SSI5/26-R+",
      "SOT5/28-R+ | SS5/28-R+ | SSI5/28-R+",
      "SOT5/30-R+ | SS5/30-R+ | SSI5/30-R+",
      "SOT6/16-R+ | SS6/16-R+ | SSI6/16-R+",
      "SOT6/24-R+ | SS6/24-R+ | SSI6/24-R+",
      "SOT6/26-R+ | SS6/26-R+ | SSI6/26-R+",
      "SOT6/28-R+ | SS6/28-R+ | SSI6/28-R+",
      "SOT6/30-R+ | SS6/30-R+ | SSI6/30-R+",
      "SOT7/16-R+ | SS7/16-R+ | SSI7/16-R+",
      "SOT7/24-R+ | SS7/24-R+ | SSI7/24-R+",
      "SOT7/26-R+ | SS7/26-R+ | SSI7/26-R+",
      "SOT7/28-R+ | SS7/28-R+ | SSI7/28-R+",
      "SOT7/30-R+ | SS7/30-R+ | SSI7/30-R+",
    ],
    combinations: {
      with_guidewire: "Add suffix - G",
      with_suture: "Add suffix - S",
      with_clamp: "Add suffix - C",
      with_hydrophilic_coating: "Add suffix - H",
    },
  },
  {
    id: "r-renal-transplant-stents-open-closed-tip",
    name: "R Renal Transplant Stents (Open Tip & Closed Tip)",
    brand: "Allwin Medical Devices",
    partnerId: "allwin",
    category: "urology",
    sub_category: "urology-consumables",
    product_type: "Renal Transplant Stents",
    is_parent_product: false,
    images: [
      "https://allwinmedical.com/wp-content/uploads/2020/11/RRenal-Transplant-Stent-Open-Tip-14.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-18-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RRenal-Transplant-Stent-Closed-Tip-15-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-15-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/R-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
    ],
    description:
      "The R+ Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopaque stent for accurate positioning, centre marking for precise placement, and a long pusher for use via ureteroscope.",
    features: [
      "Low encrustation tendency to facilitate easy removal of the stent",
      "Soft polyurethane material ensures high patient comfort",
      "Wide lumen for superior drainage",
      "Radiopaque stent to enable accurate positioning",
      "Centimetre marking to aid in stent advancement and precise placement",
      "4.7 Fr stent with a long pusher for ureteroscope use",
    ],
    variants: [
      "SOT4.7/16-R+ | SS4.7/16-R+ | SSI4.7/16-R+",
      "SOT4.7/24-R+ | SS4.7/24-R+ | SSI4.7/24-R+",
      "SOT4.7/26-R+ | SS4.7/26-R+ | SSI4.7/26-R+",
      "SOT4.7/28-R+ | SS4.7/28-R+ | SSI4.7/28-R+",
      "SOT4.7/30-R+ | SS4.7/30-R+ | SSI4.7/30-R+",
      "SOT5/16-R+ | SS5/16-R+ | SSI5/16-R+",
      "SOT5/24-R+ | SS5/24-R+ | SSI5/24-R+",
      "SOT5/26-R+ | SS5/26-R+ | SSI5/26-R+",
      "SOT5/28-R+ | SS5/28-R+ | SSI5/28-R+",
      "SOT5/30-R+ | SS5/30-R+ | SSI5/30-R+",
      "SOT6/16-R+ | SS6/16-R+ | SSI6/16-R+",
      "SOT6/24-R+ | SS6/24-R+ | SSI6/24-R+",
      "SOT6/26-R+ | SS6/26-R+ | SSI6/26-R+",
      "SOT6/28-R+ | SS6/28-R+ | SSI6/28-R+",
      "SOT6/30-R+ | SS6/30-R+ | SSI6/30-R+",
      "SOT7/16-R+ | SS7/16-R+ | SSI7/16-R+",
      "SOT7/24-R+ | SS7/24-R+ | SSI7/24-R+",
      "SOT7/26-R+ | SS7/26-R+ | SSI7/26-R+",
      "SOT7/28-R+ | SS7/28-R+ | SSI7/28-R+",
      "SOT7/30-R+ | SS7/30-R+ | SSI7/30-R+",
    ],
    combinations: {
      with_guidewire: "Add suffix - G",
      with_suture: "Add suffix - S",
      with_clamp: "Add suffix - C",
      with_hydrophilic_coating: "Add suffix - H",
    },
  },
  {
    id: "allsoft-renal-transplant-stent-open-closed-tip",
    name: "allSoft Renal Transplant Stent (Open Tip & Closed Tip)",
    brand: "Allwin Medical Devices",
    partnerId: "allwin",
    category: "urology",
    sub_category: "urology-consumables",
    product_type: "Renal Transplant Stents",
    is_parent_product: false,
    images: [
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-3.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Closed-Tip-9-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Open-Tip-12-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
    ],
    description:
      "The allSoft Renal Transplant Stent is intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. It is made of soft, biocompatible polyurethane with low encrustation tendency and is sized to fit renal transplant needs. Radiopaque markings aid precise placement. Suitable for use in transplant-related urinary drainage procedures.",
    features: [
      "Soft polyurethane material for high patient comfort",
      "Low encrustation tendency to facilitate easy removal",
      "Biocompatible material",
      "Sized for renal transplant-specific anatomy",
      "Radiopaque centremark for precise placement",
    ],
    variants: [
      "RTS-O6/12 | RTS-C6/12",
      "RTS-O6/14 | RTS-C6/14",
      "RTS-O6/16 | RTS-C6/16",
      "RTS-O7/12 | RTS-C7/12",
      "RTS-O7/14 | RTS-C7/14",
      "RTS-O7/16 | RTS-C7/16",
      "RTS-O8/12 | RTS-C8/12",
      "RTS-O8/14 | RTS-C8/14",
      "RTS-O8/16 | RTS-C8/16",
    ],
    combinations: {
      with_guidewire: "Add suffix - G",
      with_suture: "Add suffix - S",
      with_clamp: "Add suffix - C",
      with_hydrophilic_coating: "Add suffix - H",
    },
  },
  {
    id: "allsoft-multiloop-ureteral-stents-open-closed-tip",
    name: "allSoft Multiloop Ureteral Stents (Open Tip & Closed Tip)",
    brand: "Allwin Medical Devices",
    partnerId: "allwin",
    category: "urology",
    sub_category: "urology-consumables",
    product_type: "Ureteral Stents",
    is_parent_product: false,
    images: [
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Open-Tip-9.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Bladder-end-Multiloop-6-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Both-side-Multiloop-5-600x600.jpg",
      "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Closed-Tip-7-600x600.jpg",
    ],
    description:
      "The allSoft Multiloop Ureteral Stent is intended to temporarily facilitate drainage of urine from kidney to bladder by a trained physician. It offers both open and closed tip options for bladder-end or both-end multiloop configurations and is universally suitable for ureteral lengths from 22 cm to 30 cm.",
    features: [
      "Available in open and closed tip configurations",
      "Multiloop design at bladder end or both ends for improved anchorage",
      "Suitable for ureter lengths 22–30 cm",
      "Soft polyurethane for patient comfort",
      "Radiopaque marking for accurate positioning",
    ],
    variants: [
      "SOT4.7/ML | SS4.7/ML | SOT4.7/ML-ML | SS4.7/ML-ML",
      "SOT5/ML | SS5/ML | SOT5/ML-ML | SS5/ML-ML",
      "SOT6/ML | SS6/ML | SOT6/ML-ML | SS6/ML-ML",
      "SOT7/ML | SS7/ML | SOT7/ML-ML | SS7/ML-ML",
    ],
    combinations: {
      with_guidewire: "Add suffix - G",
      with_suture: "Add suffix - S",
      with_clamp: "Add suffix - C",
      with_hydrophilic_coating: "Add suffix - H",
    },
  },
  // Redpine Products
  {
    id: "redpine-single-use-video-flexible-ureteroscope",
    name: "Single-Use Video Flexible Ureteroscope",
    brand: "redpine",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Disposable Flexible Ureteroscope",
    is_parent_product: false,
    images: [
      "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg1.png",
      "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg2.png",
    ],
    description:
      "Single-Use Video Flexible Ureteroscope is designed for urological procedures where flexible access and clear visualization is necessary. The single-use design eliminates the risk of cross-contamination and reduces reprocessing costs while offering a safe, affordable endoscopic solution ideal for a wide range of stone and diagnostic procedures.",
    features: [
      "Designed for flexible ureteroscopic procedures",
      "Single-use design to eliminate cross-contamination and reprocessing costs",
      "High-quality endoscopic visualization",
      "Lightweight and easy to manoeuvre",
    ],
    applications: [
      "Ureteroscopy",
      "Stone management procedures",
      "Diagnostic upper urinary tract visualization",
    ],
    certifications: [
      "CE Mark (common for Redpine single-use endoscopes)",
      "FDA clearance on selected models (as noted in company milestones)",
    ],
    manufacturer: {
      name: "Guangzhou Redpine Medical Instrument Co., Ltd.",
      headquarters: "Guangzhou International Bioisland, Guangdong, China",
      established: "2015",
      specialty: "Single-use endoscopes and image processing platforms",
    },
    support_contact: {
      phone: "(86) 020-80927258",
      email: "info@gzredpine.com",
    },
    show_image_main: true,
  },
  {
    id: "redpine-single-use-video-flexible-cystoscope",
    name: "Single-Use Video Flexible Cystoscope",
    brand: "redpine",
    category: "urology",
    sub_category: "urology-equipment",
    product_type: "Disposable Flexible Cystoscope",
    is_parent_product: false,
    images: [
      "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg1-2.png",
      "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg2-2.png",
    ],
    description:
      "Single-Use Video Flexible Cystoscope is designed for urology procedures and provides safe, convenient cystoscopic access with clear visualization. The single-use design eliminates the risk of cross-contamination and reduces reprocessing burden while offering an easy, safe, and affordable solution.",
    features: [
      "Single-use design eliminates the potential risks of device-related cross-contamination",
      "Ergonomically designed lightweight handle for smooth manoeuvrability",
      "Highly integrated distal CMOS and dual LED provide excellent image quality",
      "Up to 210° down and 120° up bending for clear cystoscopy",
      "Slim outer diameter (OD 13.2Fr) for improved patient comfort",
      "Compatible with Redpine single-use endoscopes and RP-IPD-V800 system",
    ],
    variants: [],
    show_image_main: true,
  },
  // Excite Medical Products
  {
    id: "excitemed-drx9000-combination-system",
    name: "DRX9000-SL® Combination System",
    brand: "excite-medical",
    category: "spinal-decompression",
    sub_category: null,
    product_type: "Non-Surgical Spinal Decompression System",
    is_parent_product: false,
    images: [
      "https://www.excitemedical.com/wp-content/uploads/2024/06/21069951-drx9000c-combo-lumbar-and-cervi-300x200-1.png",
    ],
    description:
      "The DRX9000® Combination System combines the DRX9000® lumbar True Non-Surgical Spinal Decompression™ System with the DRX9000C® cervical attachment to provide both lumbar and cervical spinal decompression therapy designed to relieve pain associated with chronic back pain, neck pain, sciatica, herniated discs, bulging discs, and degenerative disc disease. :contentReference[oaicite:1]{index=1}",
    features: [
      "Combines lumbar and cervical spinal decompression therapy",
      "True Non-Surgical Spinal Decompression™ technology",
      "FDA-cleared treatment for back and neck pain conditions",
      "Adjustable traction forces for targeted disc decompression",
      "Patient monitoring and safety stop controls",
      "Ergonomic treatment table with harness support",
    ],
    technical_specifications: {
      overall_dimensions: {
        length_in: 126,
        width_in: 32.5,
        height_in: 85.5,
      },
      weight_lbs: 1780,
      crated_weight_lbs: 2530,
    },
    applications: [
      "Non-surgical treatment of chronic low back pain",
      "Cervical (neck) pain relief",
      "Sciatica and radiculopathy symptom relief",
      "Herniated and bulging disc pain management",
      "Degenerative disc disease support",
    ],
    mechanism_of_action:
      "Computer-controlled spinal traction applies graduated, targeted decompression forces to intervertebral discs to reduce pressure, promote nutrient flow, and potentially support healing, without surgical intervention. :contentReference[oaicite:2]{index=2}",
    clearances_certifications: [
      "FDA 510(k) Clearance for DRX9000®",
      "ISO 13485 Quality Management Standard",
    ],
    clinical_benefits: [
      "Non-invasive alternative to surgical decompression",
      "Customisable treatment protocols",
      "Improved patient mobility and reduced pain in many patients",
    ],
    distributor: {
      name: "Excite Medical",
      website: "https://excitemedical.com",
    },
  },
  // Concemed Products
  {
    id: "concemed-vg-h1000-video-gastroscope",
    name: "VG-H1000 Video Gastroscope",
    brand: "concemed",
    category: "endoscopy",
    sub_category: "gastroscopy",
    product_type: "Video Gastroscope",
    is_parent_product: false,
    images: [
      "https://static2.xunxiang.site/uploads/sites/2086/2024/01/133cf46c8226398dce556c386b815971.jpg",
      "https://static2.xunxiang.site/uploads/sites/2086/2024/12/0b8bb9af7b93dff2ad6dc20c28ed0c39.jpg",
      "https://static2.xunxiang.site/uploads/sites/2086/2024/12/9f8706f791ae86afe20a6fca5a4fc159.jpg",
    ],
    description:
      "The VG-H1000 Video Gastroscope is a high-performance endoscopic device designed for diagnostic and therapeutic upper gastrointestinal procedures. It offers an ultra-wide field of view, high-definition imaging, ergonomic handling, and advanced imaging compatibility to support screening, diagnosis, and treatment workflows.",
    features: [
      "Ultra-wide 145° field of view for enhanced visualization",
      "High-resolution CMOS imaging sensor",
      "Ergonomic handle design for comfortable operation",
      "Standard integrated water delivery function",
      "Compatible with VP-1000 image processor series",
      "Multiple advanced imaging modes for diagnostic and therapeutic use",
      "IPX7 waterproof design for full immersion reprocessing",
      "Excellent maneuverability and bending performance",
    ],
    variants: [],
    show_image_main: true,
  },
  {
    id: "concemed-vp-1000-video-processor",
    name: "VP-1000 Series Endoscopic Video Image Processor",
    brand: "concemed",
    category: "endoscopy",
    sub_category: "endoscopy-imaging-systems",
    product_type: "Endoscopic Video Image Processor",
    is_parent_product: true,
    images: [
      "	https://static2.xunxiang.site/uploads/sites/2086/2024/01/d398bc0c944a243ee45596058d0e22f1.jpg",
      "https://concemed-02.obs.cn-north-4.myhuaweicloud.com/f75f484ee2a6f0891fd910db69fcd63f.jpg",
    ],
    description:
      "The VP-1000 Series is an advanced endoscopic video image processor with an integrated multi-spectral LED light source. It delivers high-definition imaging with enhanced mucosal color expression and supports multiple imaging modes for screening, diagnosis, and therapeutic endoscopic procedures.",
    features: [
      "Integrated multi-spectral LED light source",
      "High-definition image processing and display",
      "Enhanced mucosal color expression",
      "Multiple advanced imaging modes",
      "8-inch touch screen control interface",
      "Integrated water delivery system",
      "Compatible with V-1000 series endoscopes",
      "Supports comprehensive endoscopic workflows",
    ],
    variants: ["VP-1000 S", "VP-1000 A", "VP-1000 P"],
    show_image_main: true,
  },
  // AdTec Healthcare Products
  {
    id: "adtec-steriplas-cold-plasma-device",
    name: "SteriPlas",
    brand: "Adtec Healthcare",
    partnerId: "adtec-premium-plasma",
    category: "wound-care",
    sub_category: "infection-management",
    product_type: "Cold Plasma Medical Device",
    is_parent_product: false,
    images: [
      "https://adtechealthcare.com/wp-content/uploads/2025/10/head2.jpg",
      "https://adtechealthcare.com/wp-content/uploads/2025/10/premiumplasma.jpg",
    ],
    description:
      "SteriPlas is a Premium Cold Plasma medical device designed to clear infection at the source by penetrating biofilms, destroying resistant bacteria, and accelerating healing more effectively than standard therapies.",
    features: [
      "Premium Cold Plasma penetrates biofilm and hard-to-reach infection sites",
      "Designed to destroy resistant bacteria including bacteria hidden in biofilm",
      "Clinically proven to reduce bacterial load by 73.5%",
      "Documented reduction of up to 100% wound size",
      "Documented reduction of up to 100% wound depth",
      "Painless treatment and causes no harm to healthy tissue",
      "Avoids the risk of antibiotic resistance",
      "18+ years of safe use with more than 10,000 treatments and 85+ peer-reviewed publications",
    ],
    applications: ["Chronic wound infections", "Surgical site infection"],
    additional_info: {
      source_url: "https://adtechealthcare.com/steriplas/",
      company_location:
        "Adtec Healthcare Limited, Unit 8, Heathlands Industrial Estate, Heathlands Close, Twickenham, TW1 4BP, UK",
      contact_phone: "+44 208 737 5500",
      contact_email: "info@adtechealthcare.com",
    },
    // show_image_main: true,
  },
  // Wego Products
  {
    id: "wego-straight-mp-joint-fusion-locking-plate-t",
    name: "Straight MP Joint Fusion Locking Plate(T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: false,
    images: ["/orthopedics/page_58_img_2.jpeg"],
    description:
      "The Straight MP Joint Fusion Locking Plate(T) is a specialized orthopedic implant designed for metacarpophalangeal (MP) joint fusion procedures. This titanium locking plate provides stable fixation for joint arthrodesis with a low-profile design and precise hole placement.",
    features: [
      "Straight design optimized for MP joint fusion",
      "Locking screw technology for angular stability",
      "Low-profile titanium construction",
      "4 holes with 3.5mm diameter for optimal fixation",
      "43.3mm length for appropriate coverage",
      "Pre-contoured anatomical design",
    ],
    technical_specifications: {
      code: "08.311.01.201820704",
      holes: "4",
      hole_diameter: "3.5mm",
      length: "43.3mm",
      material: "Titanium alloy",
      surface_finish: "Anodized blue coating",
    },
    accessories_included: [
      "Conical Head Locking screw (2.7mm)",
      "Cortex screw (2.7mm) - Flat head",
    ],
    applications: [
      "Metacarpophalangeal (MP) joint fusion",
      "Hand trauma reconstruction",
      "Degenerative joint disease treatment",
      "Post-traumatic arthritis management",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of metacarpophalangeal joint fusion procedures",
    },
    show_image_main: false,
  },
  {
    id: "wego-locking-plate-3-h-shape-t",
    name: "Locking Plate-3 (H shape)(T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_58_img_5.jpeg"],
    description:
      "The Locking Plate-3 (H shape)(T) is an innovative orthopedic locking plate with a distinctive H-shaped design for enhanced fixation in complex fracture patterns. Available in multiple sizes with varying hole configurations, this titanium plate provides exceptional stability and versatility for hand and small bone trauma reconstruction.",
    features: [
      "Unique H-shaped configuration for multi-directional support",
      "Locking screw technology for angular stability",
      "Low-profile titanium construction",
      "4 holes with variable diameters (12mm to 28mm)",
      "Multiple length options from 23.1mm to 41.1mm",
      "Pre-contoured anatomical design",
      "Superior biomechanical strength",
    ],
    variants: [
      {
        code: "08.311.01.201910704",
        holes: "4",
        hole_diameter: "12mm",
        length: "23.1mm",
      },
      {
        code: "08.311.01.201911704",
        holes: "4",
        hole_diameter: "16mm",
        length: "27.1mm",
      },
      {
        code: "08.311.01.201912704",
        holes: "4",
        hole_diameter: "20mm",
        length: "31.1mm",
      },
      {
        code: "08.311.01.201913704",
        holes: "4",
        hole_diameter: "24mm",
        length: "35.1mm",
      },
      {
        code: "08.311.01.201914704",
        holes: "4",
        hole_diameter: "28mm",
        length: "41.1mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized gold/yellow coating",
      plate_thickness: "Low-profile design",
      shape: "H-shaped configuration",
    },
    accessories_included: [
      "Cancellous Locking screw (3.5mm)",
      "Cortex screw (flat head) (3.5mm)",
    ],
    applications: [
      "Complex hand fracture fixation",
      "Small bone trauma reconstruction",
      "Metacarpal and phalangeal fractures",
      "Comminuted fracture stabilization",
      "Periarticular fracture management",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of small bone fractures and reconstructive procedures in the hand and wrist",
    },
    show_image_main: false,
  },
  {
    id: "wego-locking-plate-2-h-shape-t",
    name: "Locking Plate-2 (H shape) (T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_58_img_1.jpeg", "/orthopedics/page_58_img_6.jpeg"],
    description:
      "The Locking Plate-2 (H shape)(T) is a specialized orthopedic locking plate with an H-shaped design for optimal stability in small bone fractures. This blue anodized titanium plate features a compact design with 4 variants ranging from 18mm to 24mm hole diameters, providing versatile fixation options for hand and wrist trauma procedures.",
    features: [
      "Compact H-shaped configuration for enhanced stability",
      "Locking screw technology for superior angular stability",
      "Low-profile titanium construction",
      "4 holes with variable diameters (18mm to 24mm)",
      "Multiple length options from 29mm to 35mm",
      "Pre-contoured anatomical design",
      "Dual imaging perspectives for surgical planning",
    ],
    variants: [
      {
        code: "08.311.01.201900704",
        holes: "4",
        hole_diameter: "18mm",
        length: "29mm",
      },
      {
        code: "08.311.01.201901704",
        holes: "4",
        hole_diameter: "20mm",
        length: "31mm",
      },
      {
        code: "08.311.01.201902704",
        holes: "4",
        hole_diameter: "22mm",
        length: "33mm",
      },
      {
        code: "08.311.01.201903704",
        holes: "4",
        hole_diameter: "24mm",
        length: "35mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized blue coating",
      plate_thickness: "Low-profile design",
      shape: "H-shaped configuration",
    },
    accessories_included: [
      "Conical Head Locking screw (2.7mm)",
      "Cortex screw (2.7mm) - Flat head",
    ],
    applications: [
      "Hand and wrist fracture fixation",
      "Small bone trauma reconstruction",
      "Metacarpal fractures",
      "Phalangeal fractures",
      "Complex fracture patterns in hand surgery",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of small bone fractures in hand and wrist reconstructive procedures",
    },
    show_image_main: false,
  },
  {
    id: "wego-locking-plate-4-h-shape-t",
    name: "Locking Plate-4 (H shape) (T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_58_img_7.png", "/orthopedics/page_58_img_4.png"],
    description:
      "The Locking Plate-4 (H shape)(T) is a premium orthopedic locking plate with a distinctive H-shaped design, featuring a gold/brass anodized finish. This specialized plate is designed for micro-fracture fixation in hand and wrist surgeries, offering 4 variants with hole diameters ranging from 2mm to 8mm for precise and versatile fixation options.",
    features: [
      "Micro H-shaped configuration for delicate bone fixation",
      "Locking screw technology for maximum angular stability",
      "Ultra-low-profile titanium construction",
      "4 holes with micro diameters (2mm to 8mm)",
      "Compact length options from 22mm to 28mm",
      "Pre-contoured anatomical design",
      "Premium gold/brass anodized finish",
      "Ideal for pediatric and small bone applications",
    ],
    variants: [
      {
        code: "08.311.01.201920704",
        holes: "4",
        hole_diameter: "2mm",
        length: "22mm",
      },
      {
        code: "08.311.01.201921704",
        holes: "4",
        hole_diameter: "4mm",
        length: "24mm",
      },
      {
        code: "08.311.01.201922704",
        holes: "4",
        hole_diameter: "6mm",
        length: "26mm",
      },
      {
        code: "08.311.01.201923704",
        holes: "4",
        hole_diameter: "8mm",
        length: "28mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized gold/brass coating",
      plate_thickness: "Ultra-low-profile design",
      shape: "H-shaped micro configuration",
    },
    accessories_included: [
      "Cancellous Locking screw (3.5mm)",
      "Cortex screw (flat head) (3.5mm)",
    ],
    applications: [
      "Micro hand and wrist fracture fixation",
      "Pediatric bone trauma reconstruction",
      "Small bone fractures",
      "Distal phalangeal fractures",
      "Delicate bone repair procedures",
      "Complex micro-fracture patterns",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of micro and small bone fractures in hand, wrist, and pediatric reconstructive procedures",
    },
    show_image_main: false,
  },
  {
    id: "wego-correction-locking-plate-wedge-shape-t",
    name: "Correction Locking Plate (Wedge shape) (T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_58_img_3.jpeg"],
    description:
      "The Correction Locking Plate (Wedge shape)(T) is a specialized orthopedic implant designed for corrective osteotomy procedures. Featuring a unique wedge-shaped configuration with blue anodized titanium finish, this plate provides precise angular correction and stable fixation with 4 holes. Available in three variants with hole diameters of 4mm, 5mm, and 7mm, all maintaining a consistent 24.4mm length for optimal biomechanical performance.",
    features: [
      "Unique wedge-shaped design for angular correction",
      "Locking screw technology for superior stability",
      "Low-profile titanium construction",
      "4 holes with variable diameters (4mm, 5mm, 7mm)",
      "Consistent 24.4mm length across all variants",
      "Pre-contoured anatomical wedge design",
      "Blue anodized finish for visibility",
      "Ideal for corrective osteotomy procedures",
    ],
    variants: [
      {
        code: "08.311.01.201941704",
        holes: "4",
        hole_diameter: "4mm",
        length: "24.4mm",
      },
      {
        code: "08.311.01.201942704",
        holes: "4",
        hole_diameter: "5mm",
        length: "24.4mm",
      },
      {
        code: "08.311.01.201944704",
        holes: "4",
        hole_diameter: "7mm",
        length: "24.4mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized blue coating",
      plate_thickness: "Low-profile design",
      shape: "Wedge-shaped configuration",
      correction_angle: "Variable based on surgical requirement",
    },
    accessories_included: [
      "Conical Head Locking screw (2.7mm)",
      "Cortex screw (2.7mm) - Flat head",
    ],
    applications: [
      "Corrective osteotomy procedures",
      "Angular deformity correction",
      "Hand and wrist bone realignment",
      "Malunion correction",
      "Post-traumatic deformity correction",
      "Congenital deformity treatment",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation for corrective osteotomy and angular correction procedures in hand and wrist surgery",
    },
    show_image_main: false,
  },
  {
    id: "wego-locking-plate-2-wedge-shape-t",
    name: "Locking Plate-2 (Wedge shape)(T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_58_img_8.jpeg"],
    description:
      "The Locking Plate-2 (Wedge shape)(T) is an advanced orthopedic locking plate with a distinctive wedge configuration, featuring a premium gold/yellow anodized finish. This specialized plate is designed for precise angular correction and deformity management, offering 4 variants with hole diameters ranging from 3mm to 6mm, all maintaining a consistent 30mm length for optimal stability and surgical versatility.",
    features: [
      "Advanced wedge-shaped design for precise correction",
      "Locking screw technology for maximum stability",
      "Low-profile titanium construction",
      "4 holes with variable diameters (3mm to 6mm)",
      "Consistent 30mm length across all variants",
      "Pre-contoured anatomical wedge design",
      "Premium gold/yellow anodized finish",
      "Ideal for osteotomy and deformity correction",
    ],
    variants: [
      {
        code: "08.311.01.201952704",
        holes: "4",
        hole_diameter: "3mm",
        length: "30mm",
      },
      {
        code: "08.311.01.201953704",
        holes: "4",
        hole_diameter: "4mm",
        length: "30mm",
      },
      {
        code: "08.311.01.201954704",
        holes: "4",
        hole_diameter: "5mm",
        length: "30mm",
      },
      {
        code: "08.311.01.201955704",
        holes: "4",
        hole_diameter: "6mm",
        length: "30mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized gold/yellow coating",
      plate_thickness: "Low-profile design",
      shape: "Wedge-shaped configuration",
      correction_angle: "Variable based on surgical planning",
    },
    accessories_included: [
      "Cancellous Locking screw (3.5mm)",
      "Cortex screw (flat head) (3.5mm)",
    ],
    applications: [
      "Corrective osteotomy procedures",
      "Angular deformity correction",
      "Hand and wrist realignment",
      "Malunion correction surgery",
      "Post-traumatic deformity management",
      "Congenital bone deformity treatment",
      "Complex reconstruction procedures",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation for corrective osteotomy, angular correction, and deformity management in hand and wrist surgery",
    },
    show_image_main: false,
  },
  {
    id: "wego-calcaneus-locking-plate-10-t",
    name: "Calcaneus Locking Plate-10(T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_59_img_1.jpeg"],
    description:
      "The Calcaneus Locking Plate-10(T) is a specialized orthopedic implant designed for calcaneal fracture fixation and reconstruction. Featuring a premium gold/yellow anodized finish with an anatomically contoured T-shaped design, this plate offers three variants with 6, 8, and 10 holes, all maintaining a consistent 18mm length. The unique configuration provides optimal stability for complex calcaneal fractures and reconstruction procedures.",
    features: [
      "Anatomically contoured T-shaped design for calcaneus",
      "Locking screw technology for superior fixation",
      "Low-profile titanium construction",
      "Multiple hole configurations (6, 8, 10 holes)",
      "Consistent 18mm length across all variants",
      "Pre-contoured for anatomical fit",
      "Premium gold/yellow anodized finish",
      "Optimized for calcaneal fracture patterns",
    ],
    variants: [
      {
        code: "08.311.01.101780706",
        holes: "6",
        length: "18mm",
      },
      {
        code: "08.311.01.101780708",
        holes: "8",
        length: "18mm",
      },
      {
        code: "08.311.01.101780710",
        holes: "10",
        length: "18mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized gold/yellow coating",
      plate_thickness: "Low-profile design",
      shape: "T-shaped calcaneal configuration",
      anatomical_site: "Calcaneus (heel bone)",
    },
    accessories_included: [
      "Cancellous Locking screw (3.5mm)",
      "Cortex screw (flat head) (3.5mm)",
    ],
    applications: [
      "Calcaneal fracture fixation",
      "Intra-articular calcaneal fractures",
      "Extra-articular calcaneal fractures",
      "Comminuted heel bone fractures",
      "Calcaneal reconstruction procedures",
      "Post-traumatic calcaneal deformity correction",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of calcaneal fractures and reconstruction procedures of the heel bone",
    },
    show_image_main: false,
  },
  {
    id: "wego-variable-angle-x-shape-locking-compression-plate-tc20",
    name: "Variable Angle X-Shape Locking Compression Plate(TC20)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Compression Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_59_img_4.jpeg"],
    description:
      "The Variable Angle X-Shape Locking Compression Plate(TC20) is an advanced orthopedic implant featuring a unique X-shaped design with variable angle locking technology. With a distinctive blue anodized finish, this plate offers exceptional versatility and stability for complex fracture patterns. Available in three sizes (Small, Medium, Large), it provides multi-directional locking capabilities ideal for periarticular fractures and challenging anatomical locations.",
    features: [
      "Innovative X-shaped configuration for multi-planar stability",
      "Variable angle locking screw technology",
      "Compression and locking capabilities combined",
      "Low-profile titanium construction",
      "Three size options: Small, Medium, Large",
      "Blue anodized finish for enhanced visibility",
      "Multi-directional screw placement",
      "Optimal for complex fracture patterns",
    ],
    variants: [
      {
        code: "08.311.01.140235703",
        size: "L",
        length: "36*20mm",
      },
      {
        code: "08.311.01.140235702",
        size: "M",
        length: "32*20mm",
      },
      {
        code: "08.311.01.140235701",
        size: "S",
        length: "27*18mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized blue coating",
      plate_thickness: "Low-profile design",
      shape: "X-shaped configuration",
      locking_technology: "Variable angle locking",
      compression_capability: "Yes",
    },
    accessories_included: [
      "Locking screw-TAN (2.7mm)",
      "Variable Locking Screw (2.7mm)",
      "Cortex screw (2.7mm)",
    ],
    applications: [
      "Periarticular fracture fixation",
      "Complex multi-fragmentary fractures",
      "Metaphyseal fractures",
      "Small bone reconstruction",
      "Hand and wrist trauma",
      "Foot and ankle fractures",
      "Challenging anatomical locations",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of complex fractures with variable angle locking and compression in small bones and periarticular regions",
    },
    show_image_main: false,
  },
  {
    id: "wego-reconstruction-locking-plate-h-shape-t",
    name: "Reconstruction Locking Plate-H shape(T)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Plate",
    is_parent_product: true,
    images: ["/orthopedics/page_59_img_2.jpeg"],
    description:
      "The Reconstruction Locking Plate-H shape(T) is a versatile orthopedic implant designed for complex reconstructive procedures. Featuring a distinctive H-shaped configuration with premium gold/yellow anodized finish, this plate offers two variants with 8 and 3 holes, providing flexible fixation options for various reconstructive scenarios. The unique design allows for optimal bone fragment alignment and stable fixation in challenging anatomical reconstructions.",
    features: [
      "Versatile H-shaped design for reconstruction",
      "Locking screw technology for stable fixation",
      "Low-profile titanium construction",
      "Two configurations: 8 holes (46.3mm) and 3 holes (60.3mm)",
      "Premium gold/yellow anodized finish",
      "Malleable for anatomical contouring",
      "Ideal for complex reconstruction cases",
      "Multi-fragmentary fixation capability",
    ],
    variants: [
      {
        code: "08.311.01.201920706",
        holes: "8",
        length: "46.3mm",
      },
      {
        code: "08.311.01.201930708",
        holes: "3",
        length: "60.3mm",
      },
    ],
    technical_specifications: {
      material: "Titanium alloy",
      surface_finish: "Anodized gold/yellow coating",
      plate_thickness: "Low-profile design",
      shape: "H-shaped reconstruction configuration",
      malleability: "Can be contoured to match anatomy",
    },
    accessories_included: [
      "Cancellous Locking screw (3.5mm)",
      "Cortex screw (flat head) (3.5mm)",
    ],
    applications: [
      "Complex bone reconstruction procedures",
      "Multi-fragmentary fracture fixation",
      "Post-traumatic reconstruction",
      "Bone defect bridging",
      "Malunion and nonunion correction",
      "Revision fracture surgery",
      "Challenging anatomical reconstructions",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation for complex reconstructive procedures, multi-fragmentary fractures, and challenging anatomical scenarios",
    },
    show_image_main: false,
  },
  {
    id: "wego-variable-angle-t-shape-locking-compression-plate-tc20",
    name: "Variable Angle T-Shape Locking Compression Plate (TC20)",
    brand: "WEGO",
    partnerId: "wego",
    category: "orthopedics",
    sub_category: "foot-and-ankle",
    product_type: "Locking Compression Plate",
    is_parent_product: false,
    images: ["/orthopedics/page_59_img_6.png"],
    description:
      "The Variable Angle T-Shape Locking Compression Plate (TC20) is an innovative orthopedic implant designed for periarticular and metaphyseal fractures. Featuring a distinctive T-shaped configuration with bright blue anodized finish, this plate combines variable angle locking technology with compression capabilities. The 43mm length provides optimal coverage while the unique design allows for multi-directional screw placement, making it ideal for challenging fracture patterns in small bones.",
    features: [
      "T-shaped design for periarticular stability",
      "Variable angle locking screw technology",
      "Combined compression and locking capabilities",
      "Low-profile titanium construction",
      "43mm length for optimal coverage",
      "Bright blue anodized finish",
      "Multi-directional screw placement options",
      "Single specification for streamlined inventory",
    ],
    technical_specifications: {
      code: "08.311.01.140233700",
      specification: "单一规格 (Single specification)",
      length: "43mm",
      material: "Titanium alloy",
      surface_finish: "Anodized blue coating",
      plate_thickness: "Low-profile design",
      shape: "T-shaped configuration",
      locking_technology: "Variable angle locking",
      compression_capability: "Yes",
    },
    accessories_included: [
      "Locking screw-TAN (2.7mm)",
      "Variable Locking Screw (2.7mm)",
      "Cortex screw (2.7mm)",
    ],
    applications: [
      "Periarticular fracture fixation",
      "Metaphyseal fractures",
      "Distal radius fractures",
      "Proximal phalanx fractures",
      "Small bone trauma",
      "Hand and wrist injuries",
      "Foot and ankle fractures",
      "Complex fracture patterns",
    ],
    certifications: [],
    regulatory: {
      intended_use:
        "Internal fixation of periarticular and metaphyseal fractures with variable angle locking and compression in small bones",
    },
    show_image_main: true,
  },
];

export const companyStats = {
  yearsFounded: 1985,
  partnersCount: partners.length,
  categoriesCount: productCategories.length,
  productsCount: products.length,
  facilitiesServed: "100+",
  support: "24/7",
};

export const contactInfo = {
  companyName:
    "Riyadh International Corporation Medical Equipments & Services, Ltd",
  address: {
    street: "Orouba street, RIC Complex",
    city: "Riyadh",
    zipCode: "2324",
    country: "Kingdom of Saudi Arabia",
    poBox: "P.O. Box 223",
  },
  phone: {
    primary: "+966509698043",
    secondary: "+966114654113",
    fax: "+966114630135",
  },
  email: "ricemede@ricmedical.com.sa",
  workingHours: "Sun - Thu: 8AM - 5PM",
};
