export const partners = [
  {
    name: "BASDA",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/basda.png",
    website: "https://www.basdamri.com/",
    invertColor: false,
  },
  {
    name: "Boston Scientific",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/boston-scientific.png",
    website:
      "https://www.bostonscientific.com/en-US/patients-caregivers/device-support/penile-implants.html",
    invertColor: false,
  },
  {
    name: "Combat Medical Ltd",
    country: "United Kingdom",
    flag: "🇬🇧",
    logo: "/partners/combat-medical.png",
    website: "https://combatcancer.com/",
    invertColor: false,
  },
  {
    name: "Dornier MedTech",
    country: "Germany",
    flag: "🇩🇪",
    logo: "/partners/dornier-medtech.png",
    website: "https://www.dornier.com/",
    invertColor: false,
  },
  {
    name: "Wikkon",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/wikkon.png",
    website: "https://www.eswl.com/about-us/",
    invertColor: false,
  },
  {
    name: "Excite Medical",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/excite.png",
    website: "https://excitemedical.com/",
    invertColor: true,
  },
  {
    name: "Redpine",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/redpine.png",
    website: "https://en.redpinemed.com/",
    invertColor: false,
  },
  {
    name: "Allwin",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/allwin.jpg",
    website: "https://allwinmedical.com/",
    invertColor: false,
  },
  {
    name: "Medispec",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/medispec.svg",
    website: "https://medispec.com/",
    invertColor: true,
  },
];
