export const partners = [
  {
    id: "basda",
    name: "BASDA",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/basda.png",
    website: "https://www.basdamri.com/",
    invertColor: false,
    categories: ["medical-imaging"],
    products: ["MRI Systems", "CT Scanners", "X-Ray Equipment"],
  },
  {
    id: "boston-scientific",
    name: "Boston Scientific",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/boston-scientific.png",
    website:
      "https://www.bostonscientific.com/en-US/patients-caregivers/device-support/penile-implants.html",
    invertColor: false,
    categories: [""],
    products: ["Penile Implants", "Urological Devices", "Endourology"],
  },
  {
    id: "combat-medical",
    name: "COMBAT Medical",
    country: "United Kingdom",
    flag: "🇬🇧",
    logo: "/partners/combat-medical.png",
    website: "https://combatcancer.com/",
    invertColor: false,
    categories: ["cancer-treatment"],
    products: ["Oncology Equipment", "Cancer Therapy Systems", "Radiotherapy"],
  },
  {
    id: "dornier-medtech",
    name: "Dornier MedTech",
    country: "Germany",
    flag: "🇩🇪",
    logo: "/partners/dornier-medtech.png",
    website: "https://www.dornier.com/",
    invertColor: false,
    categories: [""],
    products: ["Lithotripsy Systems", "ESWL Technology", "Stone Treatment"],
  },
  {
    id: "wikkon",
    name: "Wikkon",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/wikkon.png",
    website: "https://www.eswl.com/about-us/",
    invertColor: false,
    categories: [""],
    products: ["ESWL Systems", "Lithotripsy", "Urological Equipment"],
  },
  {
    id: "excite-medical",
    name: "Excite Medical",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/excite.png",
    website: "https://excitemedical.com/",
    invertColor: true,
    categories: ["spinal-decompression"],
    products: [
      "Spinal Decompression Systems",
      "Therapy Equipment",
      "Treatment Solutions",
    ],
  },
  {
    id: "redpine",
    name: "Redpine",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/redpine.png",
    website: "https://en.redpinemed.com/",
    invertColor: false,
    categories: ["urology"],
    products: ["Endoscopy", "Imaging Systems", "Urological Instruments"],
  },
  {
    id: "allwin",
    name: "Allwin",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/allwin.jpg",
    website: "https://allwinmedical.com/",
    invertColor: false,
    categories: ["urology"],
    subcategories: ["urology-consumables"],
    products: [
      "Ureteral Stents",
      "Renal Transplant Stents",
      "Medical Consumables",
    ],
  },
  {
    id: "medispec",
    name: "Medispec",
    country: "USA",
    flag: "🇺🇸",
    logo: "/partners/medispec.svg",
    website: "https://medispec.com/",
    invertColor: true,
    categories: ["urology"],
    products: ["Shockwave Therapy", "ED Treatment", "Lithotripsy"],
  },
  {
    id: "potent-medical",
    name: "Potent Medical",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/potent-medical.webp",
    website: "https://www.potent-medical.com/",
    invertColor: false,
    categories: ["urology"],
    subcategories: ["urology-equipment"],
    products: ["Holmium Lasers", "Thulium Fiber Lasers", "Surgical Lasers"],
  },
  {
    id: "concemed",
    name: "ConceMed",
    country: "China",
    flag: "🇨🇳",
    logo: "/partners/concemed.png",
    website: "https://www.concemed.com/",
    invertColor: false,
    categories: ["endoscopy"],
    products: ["Endoscopy Systems", "Gastroscopes", "Colonoscopy"],
    tag: "Coming Soon",
  },
];

// Product categories for navigation
export const productCategories = [
  {
    id: "cancer-treatment",
    name: "Cancer Treatment",
    slug: "cancer-treatment",
    description: "Advanced oncology equipment and cancer therapy systems",
    icon: "Microscope",
  },
  {
    id: "urology",
    name: "Urology",
    slug: "urology",
    description: "Comprehensive urological treatment and diagnostic solutions",
    icon: "Stethoscope",
  },
  {
    id: "medical-imaging",
    name: "Medical Imaging",
    slug: "medical-imaging",
    description: "State-of-the-art diagnostic imaging systems",
    icon: "ScanLine",
  },
  {
    id: "endoscopy",
    name: "Endoscopy",
    slug: "endoscopy",
    description:
      "Advanced gastroscope and colonoscope systems for diagnostic and therapeutic procedures",
    icon: "Activity",
  },
  {
    id: "spinal-decompression",
    name: "Spinal Decompression",
    slug: "spinal-decompression",
    description: "Advanced spinal decompression therapy systems and equipment",
    icon: "Settings2",
  },
];

// Product subcategories linked to parent categories
export const productSubcategories = [
  // Urology subcategories
  {
    id: "urology-equipment",
    name: "Equipments",
    slug: "equipment",
    categoryId: "urology",
    description: "Advanced urological equipment and surgical systems",
    types: ["Lithotripsy", "Surgical Lasers", "Diagnostic Equipment"],
  },
  {
    id: "urology-consumables",
    name: "Consumables",
    slug: "consumables",
    categoryId: "urology",
    description: "Urological disposables and consumable products",
    types: ["Ureteral Stents", "Renal Transplant Stents", "Surgical Supplies"],
  },
  // Cancer Treatment subcategories
  {
    id: "cancer-treatment-systems",
    name: "Treatment Systems",
    slug: "treatment-systems",
    categoryId: "cancer-treatment",
    description: "Advanced cancer treatment and therapy systems",
    types: ["Bladder Cancer Treatment", "Chemotherapy Systems", "Radiotherapy"],
  },
  // Medical Imaging subcategories
  {
    id: "medical-imaging-systems",
    name: "Imaging Systems",
    slug: "imaging-systems",
    categoryId: "medical-imaging",
    description: "Diagnostic imaging and scanning systems",
    types: ["MRI Systems", "CT Scanners", "X-Ray Equipment"],
  },
  {
    id: "gastroscopy",
    name: "Gastroscopy",
    slug: "gastroscopy",
    categoryId: "endoscopy",
    description:
      "Gastroscopes and colonoscopes for gastrointestinal procedures",
    types: [
      "Video Gastroscopes",
      "Colonoscopy Systems",
      "Endoscopy Accessories",
    ],
  },
  {
    id: "colonoscopy",
    name: "Colonoscopy",
    slug: "colonoscopy",
    categoryId: "endoscopy",
    description:
      "Colonoscopy systems and accessories for colorectal procedures",
    types: [
      "Video Colonoscopes",
      "Colonoscopy Systems",
      "Endoscopy Accessories",
    ],
  },
  {
    id: "endoscopy-imaging-systems",
    name: "Imaging Systems",
    slug: "imaging-systems",
    categoryId: "endoscopy",
    description:
      "Video processors and imaging systems for endoscopic procedures",
    types: [
      "Video Processors",
      "Image Processing Systems",
      "LED Light Sources",
    ],
  },
];

// Company stats

// Company features
export const companyFeatures = [
  {
    icon: "Award",
    title: "ISO Certified Operations",
    description:
      "Maintaining international quality standards in all our processes and services.",
  },
  {
    icon: "Shield",
    title: "SFDA Approved Products",
    description:
      "All our medical equipment meets Saudi FDA regulatory requirements.",
  },
  {
    icon: "Headphones",
    title: "Comprehensive Support",
    description:
      "From installation to maintenance, our team provides complete technical support.",
  },
  {
    icon: "TrendingUp",
    title: "Continuous Innovation",
    description:
      "Staying ahead with the latest medical technologies and healthcare solutions.",
  },
];

// Company values (Vision, Mission, Values)
export const companyValues = [
  {
    icon: "Eye",
    title: "Our Vision",
    description:
      "Keep pace with fast-moving technology for Saudi Arabia's 2030 vision to accomplish excellence in healthy living by offering complete medical solutions.",
    gradient: "from-primary/10 to-primary/5",
    iconColor: "text-primary",
  },
  {
    icon: "Target",
    title: "Our Mission",
    description:
      "Inspire hope and improve quality of life by offering verifiable, effective professional solutions ensuring partner satisfaction.",
    gradient: "from-accent/10 to-accent/5",
    iconColor: "text-accent",
  },
  {
    icon: "Heart",
    title: "Our Values",
    description:
      "Trust, loyalty, and respect — the constant fundamentals of our commitment to excellence in healthcare partnerships.",
    gradient: "from-gold/10 to-gold/5",
    iconColor: "text-gold",
  },
];

export const productData = {
  total_products: 11,
  products: [
    // Medispec Products
    {
      id: "medispec-em1000-eswl",
      name: "EM1000™ ESWL System",
      brand: "Medispec",
      partnerId: "medispec",
      category: "urology",
      sub_category: "urology-equipment",
      product_type: "Lithotripsy",
      is_parent_product: false,
      images: [
        "/medicspec.png",
        "https://www.medispec.com/wp-content/uploads/2022/08/EM1000-36-Custom.png",
        "https://www.medispec.com/wp-content/uploads/2021/08/EM1000-Title-pic-e1638881167440.png",
        "https://www.medispec.com/wp-content/uploads/2021/10/stones.png",
      ],
      description:
        "The EM1000™ ESWL System is an advanced electromagnetic lithotripter designed for non-invasive stone management treatment with a high stone-free rate, low re-treatment rate, and outstanding clinical results. Its modular and mobile design fits a wide range of clinical environments without the need for special infrastructure. It offers real-time stone visualization and integrated imaging options.",
      features: [
        "Electromagnetic shockwave technology for efficient stone fragmentation",
        "Highest stone-free rate and lowest re-treatment rate in its class",
        "Modular, mobile design suitable for a variety of clinical settings",
        "Real-time stone visualization during treatment",
        "Versatility for both lithotripsy and endo-urology procedures",
        "Integrated X-ray and ultrasound imaging options",
      ],
      technical_specifications: {
        technology: "Electromagnetic shockwave generation",
        treatment_modes: ["Lithotripsy", "Endo-urology procedures"],
        mobility: "Modular and mobile system",
        integration: "X-ray and optional ultrasound imaging",
        clinical_benefits: [
          "High stone-free rate",
          "Low re-treatment rate",
          "Reduced treatment time",
          "Fits in small clinics to large hospitals",
        ],
      },
      accessories_included: [
        "Control console with automatic stone localization",
        "Motorized treatment table interface",
        "Integrated imaging (Visionspec™) compatibility",
        "Detachable ultrasound probe support",
      ],
      applications: [
        "Renal stone treatment",
        "Ureteric stone treatment",
        "Endo-urology procedures",
      ],
      certifications: [],
      regulatory: {
        fda_classification:
          "Class II – Extracorporeal Shock Wave Lithotripter (21 CFR 876.5990)",
        intended_use:
          "Non-invasive fragmentation of urinary tract stones including kidney and ureter stones",
      },
      distributor: {
        name: "",
        region: "",
        contact: "",
      },
    },
    // Potent Medical Products
    {
      id: "potent-hp-series-holmium-laser",
      name: "Holmium Laser HP Series High Watts",
      brand: "Potent Medical",
      partnerId: "potent-medical",
      category: "urology",
      sub_category: "urology-equipment",
      product_type: "Surgical Lasers",
      is_parent_product: true,
      images: [
        "https://www.potent-medical.com/wp-content/uploads/2024/06/Holmium-Laser-HP.png",
      ],
      description:
        "The Holmium Laser HP Series from Potent Medical is a high-power surgical laser system designed for endoscopic lithotripsy, HoLEP, and other soft-tissue procedures. It delivers superior performance with high frequency, extended pulse duration, and advanced pulse control technology, offering enhanced stone fragmentation, hemostasis, and surgical precision. The series combines powerful holmium laser energy with versatile settings for a broad range of urology and surgical applications.",
      features: [
        "High power output (up to 160W) holmium laser for efficient lithotripsy and tissue ablation",
        "Cannon Double Pulse Technology for precise control of pulse frequency and energy",
        "Wide frequency range (up to 120Hz) and high pulse energy (up to 8J)",
        "Supports both dusting stone fragmentation and HoLEP procedures",
        "Smart dual footswitch for easy parameter adjustment",
        "High resolution color touchscreen interface",
        "Quiet operation and ergonomic design for optimal OR environment",
      ],
      technical_specifications: {
        max_power_watts: 160,
        max_frequency_hz: 120,
        max_pulse_energy_joules: 8.0,
        wavelength_nm: 2100,
        pulse_control: "Cannon Double Pulse Technology",
        applications: [
          "Endoscopic lithotripsy",
          "HoLEP (Holmium Laser Enucleation of the Prostate)",
          "Soft tissue vaporization and incision",
          "Urology, Gynecology, ENT and general soft-tissue surgery",
        ],
      },
      benefits_for_surgeon: [
        "High efficiency for stone treatment and BPH surgery",
        "Intuitive user controls and flexible settings options",
        "Minimal retropulsion during lithotripsy",
        "Ergonomic console and easy integration into operating suites",
      ],
      advantages_for_patient: [
        "Minimally invasive procedures",
        "Reduced bleeding and faster recovery",
        "Shorter anesthesia time",
        "High precision and safety",
      ],
      applications: [
        "Ureteroscopic stone treatment",
        "Percutaneous nephrolithotomy support",
        "Benign prostatic hyperplasia (BPH) procedures",
        "Soft tissue surgical applications",
      ],
      compliance_certifications: ["CE Mark", "ISO 13485"],
      accessories: [
        "Laser fibers (various sizes)",
        "Footswitch",
        "Fiber connectors",
      ],
    },
    {
      id: "potent-hz-series-holmium-laser",
      name: "Holmium Laser HZ Series",
      brand: "Potent Medical",
      partnerId: "potent-medical",
      category: "urology",
      sub_category: "urology-equipment",
      product_type: "Surgical Lasers",
      is_parent_product: true,
      images: [
        "https://www.potent-medical.com/wp-content/uploads/2024/01/123-2.png",
      ],
      description:
        "The Holmium Laser HZ Series from Potent Medical is a versatile surgical laser designed for urology procedures including stone lithotripsy, BPH treatment, and soft tissue incision. It operates at the efficient 2100 nm wavelength with adjustable frequency, energy, and pulse duration to address a broad range of surgical needs in urology and beyond. The intuitive touchscreen interface and internal cooling ensure reliable performance in diverse clinical environments.",
      features: [
        "Versatile surgical laser system tailored for urology",
        "Operates at 2100 nm wavelength with high water absorption and reduced penetration compared to other lasers",
        "Adjustable frequency and pulse duration for enhanced flexibility in procedures",
        "Intuitive touchscreen interface for quick parameter adjustment",
        "Internal cooling system for stable performance",
        "Quiet operation with reduced noise",
        "Compatible with a wide range of laser fibers from 150 μm to 1000 μm",
      ],
      technical_specifications: {
        wavelength_nm: 2100,
        max_power_watts: 90,
        pulse_frequency_hz: "5–40",
        pulse_energy_joules: "0.1–4.5",
        laser_type: "Holmium (Ho:YAG)",
        cooling_system: "Internal cooling",
      },
      applications: [
        "Laser lithotripsy for urinary stones",
        "Benign prostatic hyperplasia (BPH) treatment",
        "Soft tissue incision and excision",
        "General urology surgical procedures",
      ],
      advantages_for_surgeon: [
        "Adjustable settings allow tailored energy delivery",
        "Intuitive control panel simplifies intraoperative adjustments",
        "Stable performance with internal cooling system",
      ],
      compliance_certifications: ["CE Certification", "ISO13485"],
    },
    {
      id: "potent-thulium-fiber-laser-pulsemaster",
      name: "Thulium Fiber Laser PulseMaster",
      brand: "Potent Medical",
      partnerId: "potent-medical",
      category: "urology",
      sub_category: "urology-equipment",
      product_type: "Surgical Lasers",
      is_parent_product: false,
      images: [
        "https://www.potent-medical.com/wp-content/uploads/2024/06/%E5%AE%B9%E5%99%A8-1@1x-2024-10-09T171925.625.webp",
      ],
      description:
        "The Thulium Fiber Laser PulseMaster by Potent Medical is an advanced laser system designed to deliver high-precision, efficient performance for stone management and soft tissue procedures. It features ultra-long pulse technology, air cooling, intuitive touch screen controls, a smart fiber connector, and dual pedal footswitch modes for rapid switching between dusting and fragmentation. It combines safety, speed, and efficiency in one versatile surgical laser platform. :contentReference[oaicite:0]{index=0}",
      features: [
        "Ultra-long pulse laser technology for precise targeting with reduced retropulsion and improved stone dusting efficiency",
        "10-inch intuitive touch screen interface",
        "Air cooling system for compact footprint and low noise without fluid management",
        "Smart fiber identification system",
        "Dual pedal footswitch for fast mode switching between dusting and fragmentation",
        "Reduced long-term costs and low maintenance requirements",
      ],
      technical_specifications: {
        technology: "Thulium Fiber Laser (TFL)",
        pulse_mode: "Ultra-long pulse",
        cooling_system: "Air cooling",
        control_interface: "10-inch touch screen",
        footswitch_modes: ["Dusting", "Fragmentation"],
      },
      applications: [
        "Laser lithotripsy for urinary stones",
        "Soft tissue incision and ablation",
        "Benign prostatic hyperplasia (BPH) procedures",
        "Urology surgical applications",
      ],
      advantages_for_surgeon: [
        "Precise energy delivery with reduced stone retropulsion",
        "Intuitive control and adjustable parameters",
        "Small footprint and quiet operation",
        "Smart fiber connectivity for workflow efficiency",
      ],
      benefits_for_patient: [
        "Enhanced surgical precision",
        "Lower complication risk",
        "Faster recovery times",
      ],
      certifications: [],
      distributor: {
        name: "",
        region: "",
        contact: "",
      },
    },
    // Combat Medical Products
    {
      id: "combat-brs-hivec-bladder-cancer-system",
      name: "COMBAT BRS HIVEC® Bladder Cancer System",
      brand: "COMBAT Medical",
      partnerId: "combat-medical",
      category: "cancer-treatment",
      sub_category: "cancer-treatment-systems",
      product_type: "Bladder Cancer Treatment",
      is_parent_product: false,
      images: [
        "http://combatcancer.com/wp-content/uploads/2021/05/BRS_V5_C.jpg",
      ],
      description:
        "The COMBAT BRS HIVEC® Bladder Cancer System is an advanced conductive bladder recirculation platform designed to deliver Hyperthermic Intra-VEsical Chemotherapy (HIVEC®) for patients with non-muscle invasive bladder cancer (NMIBC). It precisely controls intravesical chemotherapy temperature and circulation to enhance drug efficacy, improve homogeneous heat distribution, and optimise clinical outcomes.",
      features: [
        "Closed conductive recirculation system for consistent drug and heat distribution",
        "Accurate temperature control within ±0.2°C of set target",
        "Touchscreen user interface with real-time monitoring of temperature and pressure",
        "Built-in safety alarms for high/low temperature and pressure",
        "Patented aluminium heat exchanger for efficient heat transfer",
        "Peristaltic pump for smooth, continuous, reversible recirculation",
        "Flexible 16F 3-way catheter with coude tip for patient comfort",
      ],
      technical_specifications: {
        temperature_control_range_celsius: "41–44 °C",
        temperature_stability: "±0.2°C",
        catheter_size_fr: "16F 3-way",
        pressure_monitoring: "Continuous with automated safety cutoff",
        monitoring_interface: "Touchscreen with graphical readout",
        recirculation_system: "Peristaltic pump with bubble trap chamber",
        data_export: "USB (CSV/TXT formats)",
      },
      applications: [
        "Hyperthermic intravesical chemotherapy (HIVEC®) for NMIBC patients",
        "Alternative treatment for patients unfit for, intolerant of, or refusing BCG therapy",
        "Adjunct therapy post-TURBT in bladder cancer management",
      ],
      clinical_benefits: [
        "Promotes homogeneous heated chemotherapy delivery throughout the bladder",
        "Potential to improve drug efficacy compared with cold chemotherapy alone",
        "System designed for patient comfort at low pressure and flow rates",
        "Promising safety and tolerability profile in interim clinical data",
      ],
      certifications: [
        "IEC/UL 60601-1",
        "IEC 60601-1-2",
        "EN 55011",
        "CAN/CSA-C22.2",
        "CE Mark",
      ],
      references: [
        "HIVEC® stands for Hyperthermic Intra-VEsical Chemotherapy and is used as a bladder-sparing treatment option in intermediate and high-risk NMIBC patients, where BCG is intolerable or unavailable. :contentReference[oaicite:1]{index=1}",
        "The COMBAT BRS device uses a patented aluminium heat exchanger to deliver accurate and uniform heated chemotherapy distribution. :contentReference[oaicite:2]{index=2}",
        "Clinical data suggest a favorable patient tolerability and comparable side-effect profile to standard intravesical therapies. :contentReference[oaicite:3]{index=3}",
      ],
      distributor: {
        name: "Global Combat Medical Network",
        website: "https://combatcancer.com",
      },
    },
    // BASDA Products
    {
      id: "basda-bti-050-0-5t-permanent-magnet-mri",
      name: "BTI-050 0.5T Wide Open C-Shape Permanent Magnet MRI Machine",
      brand: "BASDA",
      partnerId: "basda",
      category: "medical-imaging",
      sub_category: "medical-imaging-systems",
      product_type: "MRI Systems",
      is_parent_product: false,
      images: [
        "https://www.basdamri.com/photo/ps32394899-wide_open_c_shape_0_5_tesla_permanent_magnet_mri_machine_bti_050.jpg",
      ],
      description:
        "The BASDA BTI-050 is a 0.5 Tesla wide open C-shape permanent magnet MRI system designed to deliver comfortable patient accessibility with reliable diagnostic imaging performance. Its open magnet design supports easier positioning, improved patient comfort, and broad clinical usability for routine imaging applications.",
      features: [
        "0.5 Tesla permanent magnet MRI system",
        "Wide open C-shape design for improved patient comfort and accessibility",
        "Designed for stable and consistent imaging performance",
        "Suitable for routine diagnostic imaging applications",
        "Optimised workflow for hospitals and imaging centres",
      ],
      technical_specifications: {
        magnetic_field_tesla: 0.5,
        magnet_type: "Permanent Magnet",
        magnet_structure: "Wide Open C-Shape",
        patient_access: "Open design for improved positioning",
        clinical_use: "Routine diagnostic MRI imaging",
      },
      system_components: [
        "Permanent magnet system",
        "RF system",
        "Gradient system",
        "Patient table",
        "Computer workstation",
        "MRI control software",
      ],
      applications: [
        "Routine diagnostic MRI imaging",
        "Musculoskeletal imaging",
        "Brain and neurological imaging",
        "Abdominal imaging",
      ],
      certifications: [],
      additional_info: {
        place_of_origin: "China",
        minimum_order_quantity: "1 set",
        delivery_time_days: "30-45 Days",
      },
    },
    {
      id: "basda-bstar-150f-1-5t-no-helium-superconducting-mri",
      name: "Bstar-150F 1.5T No-Helium Superconducting MRI Scanner",
      brand: "BASDA",
      partnerId: "basda",
      category: "medical-imaging",
      sub_category: "medical-imaging-systems",
      product_type: "MRI Systems",
      is_parent_product: false,
      images: [
        "https://www.basdamri.com/photo/ps33865573-1_5_tesla_no_helium_superconducting_mri_scanner_open_superconductive_mri_bstar_150f.jpg",
      ],
      description:
        "The BASDA Bstar-150F is a 1.5 Tesla superconducting MRI scanner engineered without the need for liquid helium, significantly reducing operational constraints and dependency on helium supply. It provides high magnetic field stability and excellent imaging performance with an active shielding design suitable for advanced clinical diagnostics. :contentReference[oaicite:0]{index=0}",
      features: [
        "Helium-free superconducting magnet eliminates the need for liquid helium consumption. :contentReference[oaicite:1]{index=1}",
        "1.5 Tesla magnetic field for high-resolution diagnostic imaging. :contentReference[oaicite:2]{index=2}",
        "Active shielding method and modular design for easier installation and reduced footprint. :contentReference[oaicite:3]{index=3}",
        "Automatic field drop and restoration in power interruptions. :contentReference[oaicite:4]{index=4}",
        "Supports cloud interconnection for remote monitoring and control. :contentReference[oaicite:5]{index=5}",
      ],
      technical_specifications: {
        magnetic_field_tesla: 1.5,
        liquid_helium_liters: 0,
        magnet_type: "Superconductive (niobium-titanium alloys)",
        shielding_method: "Active",
        shimming_method: "Active + Passive + Dynamic",
        homogeneity_ppm: "≤0.01 (10 cm DSV)",
        field_stability_ppm_per_h: "≤0.1",
        inner_diameter_mm: 600,
        "5_gauss_fringe_field_m": "≤2.5 x 2.5 x 4.0",
        power_consumption_kw: "45",
      },
      system_components: [
        "No-helium superconducting magnet",
        "RF sub system with 8/16 channel receiver",
        "Gradient sub system with self-shielding coils",
        "Motor-driven patient table",
        "Water chiller cooling system",
        "Intelligent monitoring and control software",
      ],
      applications: [
        "Body and neurological diagnostic MRI",
        "Abdominal imaging",
        "Musculoskeletal imaging",
        "Cardiovascular MRI",
      ],
      certifications: ["ISO13485"],
      additional_info: {
        place_of_origin: "China",
        minimum_order_quantity: "1 set",
        delivery_time_days: "30-45 Days",
      },
    },
    {
      id: "basda-bstar-050-0-5t-dual-post-superconducting-open-mri",
      name: "Dual Post Superconducting 0.5 Tesla Open MRI Machine Bstar-050",
      brand: "BASDA",
      partnerId: "basda",
      category: "medical-imaging",
      sub_category: "medical-imaging-systems",
      product_type: "MRI Systems",
      is_parent_product: false,
      images: [
        "https://www.basdamri.com/photo/ps32748164-dual_post_superconducting_0_5_tesla_open_mri_machine_bstar_050.jpg",
      ],
      description:
        "The BASDA Bstar-050 is a dual post superconducting 0.5 Tesla open MRI system launched in 2016. It is designed to provide a low-cost, low-power-consumption open MRI solution with faster scanning speed than permanent magnet MRI and image quality close to 1.5T superconductive MRI, while reducing patient claustrophobia through its open magnet design.",
      features: [
        "0.5 Tesla superconductive open MRI scanner with dual post magnet design",
        "Low electricity cost compared to conventional 1.5T MRI systems",
        "Configured with Sumitomo 4K cold head to provide zero consumption of liquid helium",
        "Faster scanning time than permanent magnet MRI systems",
        "Image quality better than permanent magnet MRI and close to 1.5T superconductive MRI level",
        "Open magnet design reduces claustrophobic fear and patient involuntary movement artifacts",
        "Self-shielding gradient coil with high duty cycle gradient amplifier system",
        "Eddy zero technology and software algorithm to eliminate eddy current effects",
        "Special hardware noise reduction design reducing gradient noise up to 66%",
        "Air cooling gradient system to reduce maintenance cost",
        "4-channel RF receiving combined with parallel sampling and DDC digital direct sampling",
        "Supports advanced sequences including MRA, MRU/MRCP/MRM, and DWI imaging",
        "E-alarm real-time monitoring for magnet pressure, temperature, and liquid helium level with phone alerts",
      ],
      technical_specifications: {
        magnetic_field_tesla: 0.5,
        magnet_shape: "Dual Post",
        magnet_type: "Superconductive Magnet",
        vertical_gap_cm: 42,
        cooling: "Water-cooled helium",
        rf_channels: 4,
        gradient_cooling: "Air cooling",
        liquid_helium_consumption: "Zero (with 4K cold head)",
      },
      system_components: [
        "Dual post superconductive open magnet system",
        "Self-shielding gradient coil system",
        "High duty cycle gradient amplifier system",
        "4-channel RF receiving subsystem",
        "Parallel acquisition and DDC digital direct sampling technology",
        "Noise reduction hardware design for gradient system",
        "Interactive scan system with full-body scan kit and sequences",
        "E-alarm monitoring system (pressure, temperature, helium level)",
      ],
      applications: [
        "Routine full-body MRI scanning",
        "MR Angiography (MRA)",
        "MR Urography (MRU)",
        "MR Cholangiopancreatography (MRCP)",
        "MR Mammography (MRM)",
        "Diffusion Weighted Imaging (DWI)",
      ],
      certifications: ["CE", "ISO13485"],
      additional_info: {
        place_of_origin: "Guangdong, P.R.C.",
        model_number: "Bstar-050",
        minimum_order_quantity: "1 set",
        price: "Negotiable",
        packaging_details: "1 unit/wooden box",
        delivery_time_days: "30-45 Days",
        payment_terms: [
          "Credit card",
          "Paypal",
          "T/T",
          "Western Union",
          "MoneyGram",
        ],
        supply_ability: "200 machines per year",
      },
    },
    // Allwin Medical Devices Products
    {
      id: "Allsoft-ureteral-stents-open-closed-intraoperative",
      name: "allSoft Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
      brand: "Allwin Medical Devices",
      partnerId: "allwin",
      category: "urology",
      sub_category: "urology-consumables",
      product_type: "Ureteral Stents",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Open-Tip-13.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Open-Tip-14-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Closed-Tip-13-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Closed-Tip-12-600x600.jpg",
      ],
      description:
        "The AllSoft Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopacity for accurate positioning, and centimeter markings for precise placement.",
      features: [
        "Low encrustation tendency to facilitate easy removal of the stent",
        "Soft polyurethane material ensures high patient comfort",
        "Wide lumen for superior drainage",
        "Radiopaque stent to enable accurate positioning",
        "Centimeter marking to aid in stent advancement and precise placement",
      ],
      variants: [
        "SOT4.7/16 | SS4.7/16 | SSI4.7/16",
        "SOT4.7/24 | SS4.7/24 | SSI4.7/24",
        "SOT4.7/26 | SS4.7/26 | SSI4.7/26",
        "SOT4.7/28 | SS4.7/28 | SSI4.7/28",
        "SOT4.7/30 | SS4.7/30 | SSI4.7/30",
        "SOT5/16 | SS5/16 | SSI5/16",
        "SOT5/24 | SS5/24 | SSI5/24",
        "SOT5/26 | SS5/26 | SSI5/26",
        "SOT5/28 | SS5/28 | SSI5/28",
        "SOT5/30 | SS5/30 | SSI5/30",
        "SOT6/16 | SS6/16 | SSI6/16",
        "SOT6/24 | SS6/24 | SSI6/24",
        "SOT6/26 | SS6/26 | SSI6/26",
        "SOT6/28 | SS6/28 | SSI6/28",
        "SOT6/30 | SS6/30 | SSI6/30",
        "SOT7/16 | SS7/16 | SSI7/16",
        "SOT7/24 | SS7/24 | SSI7/24",
        "SOT7/26 | SS7/26 | SSI7/26",
        "SOT7/28 | SS7/28 | SSI7/28",
        "SOT7/30 | SS7/30 | SSI7/30",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "r-plus-ureteral-stents-open-closed-intraoperative",
      name: "R+ Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
      brand: "Allwin Medical Devices",
      partnerId: "allwin",
      category: "urology",
      sub_category: "urology-consumables",
      product_type: "Ureteral Stents",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-16.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-16.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-17.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-14-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-13-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/R-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
      ],
      description:
        "The R+ Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopaque stent for accurate positioning, centre marking for precise placement, and a long pusher for use via ureteroscope.",
      features: [
        "Low encrustation tendency to facilitate easy removal of the stent",
        "Soft polyurethane material ensures high patient comfort",
        "Wide lumen for superior drainage",
        "Radiopaque stent to enable accurate positioning",
        "Centimetre marking to aid in stent advancement and precise placement",
        "4.7 Fr stent with a long pusher for ureteroscope use",
      ],
      variants: [
        "SOT4.7/16-R+ | SS4.7/16-R+ | SSI4.7/16-R+",
        "SOT4.7/24-R+ | SS4.7/24-R+ | SSI4.7/24-R+",
        "SOT4.7/26-R+ | SS4.7/26-R+ | SSI4.7/26-R+",
        "SOT4.7/28-R+ | SS4.7/28-R+ | SSI4.7/28-R+",
        "SOT4.7/30-R+ | SS4.7/30-R+ | SSI4.7/30-R+",
        "SOT5/16-R+ | SS5/16-R+ | SSI5/16-R+",
        "SOT5/24-R+ | SS5/24-R+ | SSI5/24-R+",
        "SOT5/26-R+ | SS5/26-R+ | SSI5/26-R+",
        "SOT5/28-R+ | SS5/28-R+ | SSI5/28-R+",
        "SOT5/30-R+ | SS5/30-R+ | SSI5/30-R+",
        "SOT6/16-R+ | SS6/16-R+ | SSI6/16-R+",
        "SOT6/24-R+ | SS6/24-R+ | SSI6/24-R+",
        "SOT6/26-R+ | SS6/26-R+ | SSI6/26-R+",
        "SOT6/28-R+ | SS6/28-R+ | SSI6/28-R+",
        "SOT6/30-R+ | SS6/30-R+ | SSI6/30-R+",
        "SOT7/16-R+ | SS7/16-R+ | SSI7/16-R+",
        "SOT7/24-R+ | SS7/24-R+ | SSI7/24-R+",
        "SOT7/26-R+ | SS7/26-R+ | SSI7/26-R+",
        "SOT7/28-R+ | SS7/28-R+ | SSI7/28-R+",
        "SOT7/30-R+ | SS7/30-R+ | SSI7/30-R+",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "r-renal-transplant-stents-open-closed-tip",
      name: "R Renal Transplant Stents (Open Tip & Closed Tip)",
      brand: "Allwin Medical Devices",
      partnerId: "allwin",
      category: "urology",
      sub_category: "urology-consumables",
      product_type: "Renal Transplant Stents",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/RRenal-Transplant-Stent-Open-Tip-14.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-18-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RRenal-Transplant-Stent-Closed-Tip-15-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-15-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/R-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
      ],
      description:
        "The R+ Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopaque stent for accurate positioning, centre marking for precise placement, and a long pusher for use via ureteroscope.",
      features: [
        "Low encrustation tendency to facilitate easy removal of the stent",
        "Soft polyurethane material ensures high patient comfort",
        "Wide lumen for superior drainage",
        "Radiopaque stent to enable accurate positioning",
        "Centimetre marking to aid in stent advancement and precise placement",
        "4.7 Fr stent with a long pusher for ureteroscope use",
      ],
      variants: [
        "SOT4.7/16-R+ | SS4.7/16-R+ | SSI4.7/16-R+",
        "SOT4.7/24-R+ | SS4.7/24-R+ | SSI4.7/24-R+",
        "SOT4.7/26-R+ | SS4.7/26-R+ | SSI4.7/26-R+",
        "SOT4.7/28-R+ | SS4.7/28-R+ | SSI4.7/28-R+",
        "SOT4.7/30-R+ | SS4.7/30-R+ | SSI4.7/30-R+",
        "SOT5/16-R+ | SS5/16-R+ | SSI5/16-R+",
        "SOT5/24-R+ | SS5/24-R+ | SSI5/24-R+",
        "SOT5/26-R+ | SS5/26-R+ | SSI5/26-R+",
        "SOT5/28-R+ | SS5/28-R+ | SSI5/28-R+",
        "SOT5/30-R+ | SS5/30-R+ | SSI5/30-R+",
        "SOT6/16-R+ | SS6/16-R+ | SSI6/16-R+",
        "SOT6/24-R+ | SS6/24-R+ | SSI6/24-R+",
        "SOT6/26-R+ | SS6/26-R+ | SSI6/26-R+",
        "SOT6/28-R+ | SS6/28-R+ | SSI6/28-R+",
        "SOT6/30-R+ | SS6/30-R+ | SSI6/30-R+",
        "SOT7/16-R+ | SS7/16-R+ | SSI7/16-R+",
        "SOT7/24-R+ | SS7/24-R+ | SSI7/24-R+",
        "SOT7/26-R+ | SS7/26-R+ | SSI7/26-R+",
        "SOT7/28-R+ | SS7/28-R+ | SSI7/28-R+",
        "SOT7/30-R+ | SS7/30-R+ | SSI7/30-R+",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "allsoft-renal-transplant-stent-open-closed-tip",
      name: "allSoft Renal Transplant Stent (Open Tip & Closed Tip)",
      brand: "Allwin Medical Devices",
      partnerId: "allwin",
      category: "urology",
      sub_category: "urology-consumables",
      product_type: "Renal Transplant Stents",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-3.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Closed-Tip-9-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Open-Tip-12-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
      ],
      description:
        "The allSoft Renal Transplant Stent is intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. It is made of soft, biocompatible polyurethane with low encrustation tendency and is sized to fit renal transplant needs. Radiopaque markings aid precise placement. Suitable for use in transplant-related urinary drainage procedures.",
      features: [
        "Soft polyurethane material for high patient comfort",
        "Low encrustation tendency to facilitate easy removal",
        "Biocompatible material",
        "Sized for renal transplant-specific anatomy",
        "Radiopaque centremark for precise placement",
      ],
      variants: [
        "RTS-O6/12 | RTS-C6/12",
        "RTS-O6/14 | RTS-C6/14",
        "RTS-O6/16 | RTS-C6/16",
        "RTS-O7/12 | RTS-C7/12",
        "RTS-O7/14 | RTS-C7/14",
        "RTS-O7/16 | RTS-C7/16",
        "RTS-O8/12 | RTS-C8/12",
        "RTS-O8/14 | RTS-C8/14",
        "RTS-O8/16 | RTS-C8/16",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "allsoft-multiloop-ureteral-stents-open-closed-tip",
      name: "allSoft Multiloop Ureteral Stents (Open Tip & Closed Tip)",
      brand: "Allwin Medical Devices",
      partnerId: "allwin",
      category: "urology",
      sub_category: "urology-consumables",
      product_type: "Ureteral Stents",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Open-Tip-9.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Bladder-end-Multiloop-6-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Both-side-Multiloop-5-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Closed-Tip-7-600x600.jpg",
      ],
      description:
        "The allSoft Multiloop Ureteral Stent is intended to temporarily facilitate drainage of urine from kidney to bladder by a trained physician. It offers both open and closed tip options for bladder-end or both-end multiloop configurations and is universally suitable for ureteral lengths from 22 cm to 30 cm.",
      features: [
        "Available in open and closed tip configurations",
        "Multiloop design at bladder end or both ends for improved anchorage",
        "Suitable for ureter lengths 22–30 cm",
        "Soft polyurethane for patient comfort",
        "Radiopaque marking for accurate positioning",
      ],
      variants: [
        "SOT4.7/ML | SS4.7/ML | SOT4.7/ML-ML | SS4.7/ML-ML",
        "SOT5/ML | SS5/ML | SOT5/ML-ML | SS5/ML-ML",
        "SOT6/ML | SS6/ML | SOT6/ML-ML | SS6/ML-ML",
        "SOT7/ML | SS7/ML | SOT7/ML-ML | SS7/ML-ML",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    // Redpine Products
    {
      id: "redpine-single-use-video-flexible-ureteroscope",
      name: "Single-Use Video Flexible Ureteroscope",
      brand: "redpine",
      category: "urology",
      sub_category: "urology-equipment",
      product_type: "Disposable Flexible Ureteroscope",
      is_parent_product: false,
      images: [
        "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg1.png",
        "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg2.png",
      ],
      description:
        "Single-Use Video Flexible Ureteroscope is designed for urological procedures where flexible access and clear visualization is necessary. The single-use design eliminates the risk of cross-contamination and reduces reprocessing costs while offering a safe, affordable endoscopic solution ideal for a wide range of stone and diagnostic procedures.:contentReference[oaicite:0]{index=0}",
      features: [
        "Designed for flexible ureteroscopic procedures",
        "Single-use design to eliminate cross-contamination and reprocessing costs",
        "High-quality endoscopic visualization",
        "Lightweight and easy to manoeuvre",
      ],
      applications: [
        "Ureteroscopy",
        "Stone management procedures",
        "Diagnostic upper urinary tract visualization",
      ],
      certifications: [
        "CE Mark (common for Redpine single-use endoscopes)",
        "FDA clearance on selected models (as noted in company milestones)",
      ],
      manufacturer: {
        name: "Guangzhou Redpine Medical Instrument Co., Ltd.",
        headquarters: "Guangzhou International Bioisland, Guangdong, China",
        established: "2015",
        specialty: "Single-use endoscopes and image processing platforms",
      },
      support_contact: {
        phone: "(86) 020-80927258",
        email: "info@gzredpine.com",
      },
      show_image_main: true,
    },
    {
      id: "redpine-single-use-video-flexible-cystoscope",
      name: "Single-Use Video Flexible Cystoscope",
      brand: "redpine",
      category: "urology",
      sub_category: "urology-equipment",
      product_type: "Disposable Flexible Cystoscope",
      is_parent_product: false,
      images: [
        "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg1-2.png",
        "https://en.redpinemed.com/gzrpyl202311303965/uploadfiles/image/proinfoimg2-2.png",
      ],
      description:
        "Single-Use Video Flexible Cystoscope is designed for urology procedures and provides safe, convenient cystoscopic access with clear visualization. The single-use design eliminates the risk of cross-contamination and reduces reprocessing burden while offering an easy, safe, and affordable solution.",
      features: [
        "Single-use design eliminates the potential risks of device-related cross-contamination",
        "Ergonomically designed lightweight handle for smooth manoeuvrability",
        "Highly integrated distal CMOS and dual LED provide excellent image quality",
        "Up to 210° down and 120° up bending for clear cystoscopy",
        "Slim outer diameter (OD 13.2Fr) for improved patient comfort",
        "Compatible with Redpine single-use endoscopes and RP-IPD-V800 system",
      ],
      variants: [],
      show_image_main: true,
    },
    // Excite Medical Products
    {
      id: "excitemed-drx9000-combination-system",
      name: "DRX9000-SL® Combination System",
      brand: "excite-medical",
      category: "spinal-decompression",
      sub_category: null,
      product_type: "Non-Surgical Spinal Decompression System",
      is_parent_product: false,
      images: [
        "https://www.excitemedical.com/wp-content/uploads/2024/06/21069951-drx9000c-combo-lumbar-and-cervi-300x200-1.png",
      ],
      description:
        "The DRX9000® Combination System combines the DRX9000® lumbar True Non-Surgical Spinal Decompression™ System with the DRX9000C® cervical attachment to provide both lumbar and cervical spinal decompression therapy designed to relieve pain associated with chronic back pain, neck pain, sciatica, herniated discs, bulging discs, and degenerative disc disease. :contentReference[oaicite:1]{index=1}",
      features: [
        "Combines lumbar and cervical spinal decompression therapy",
        "True Non-Surgical Spinal Decompression™ technology",
        "FDA-cleared treatment for back and neck pain conditions",
        "Adjustable traction forces for targeted disc decompression",
        "Patient monitoring and safety stop controls",
        "Ergonomic treatment table with harness support",
      ],
      technical_specifications: {
        overall_dimensions: {
          length_in: 126,
          width_in: 32.5,
          height_in: 85.5,
        },
        weight_lbs: 1780,
        crated_weight_lbs: 2530,
      },
      applications: [
        "Non-surgical treatment of chronic low back pain",
        "Cervical (neck) pain relief",
        "Sciatica and radiculopathy symptom relief",
        "Herniated and bulging disc pain management",
        "Degenerative disc disease support",
      ],
      mechanism_of_action:
        "Computer-controlled spinal traction applies graduated, targeted decompression forces to intervertebral discs to reduce pressure, promote nutrient flow, and potentially support healing, without surgical intervention. :contentReference[oaicite:2]{index=2}",
      clearances_certifications: [
        "FDA 510(k) Clearance for DRX9000®",
        "ISO 13485 Quality Management Standard",
      ],
      clinical_benefits: [
        "Non-invasive alternative to surgical decompression",
        "Customisable treatment protocols",
        "Improved patient mobility and reduced pain in many patients",
      ],
      distributor: {
        name: "Excite Medical",
        website: "https://excitemedical.com",
      },
    },
    // Concemed Products
    {
      id: "concemed-vg-h1000-video-gastroscope",
      name: "VG-H1000 Video Gastroscope",
      brand: "concemed",
      category: "endoscopy",
      sub_category: "gastroscopy",
      product_type: "Video Gastroscope",
      is_parent_product: false,
      images: [
        "https://static2.xunxiang.site/uploads/sites/2086/2024/01/133cf46c8226398dce556c386b815971.jpg",
        "https://static2.xunxiang.site/uploads/sites/2086/2024/12/0b8bb9af7b93dff2ad6dc20c28ed0c39.jpg",
        "https://static2.xunxiang.site/uploads/sites/2086/2024/12/9f8706f791ae86afe20a6fca5a4fc159.jpg",
      ],
      description:
        "The VG-H1000 Video Gastroscope is a high-performance endoscopic device designed for diagnostic and therapeutic upper gastrointestinal procedures. It offers an ultra-wide field of view, high-definition imaging, ergonomic handling, and advanced imaging compatibility to support screening, diagnosis, and treatment workflows.",
      features: [
        "Ultra-wide 145° field of view for enhanced visualization",
        "High-resolution CMOS imaging sensor",
        "Ergonomic handle design for comfortable operation",
        "Standard integrated water delivery function",
        "Compatible with VP-1000 image processor series",
        "Multiple advanced imaging modes for diagnostic and therapeutic use",
        "IPX7 waterproof design for full immersion reprocessing",
        "Excellent maneuverability and bending performance",
      ],
      variants: [],
      show_image_main: true,
    },
    {
      id: "concemed-vp-1000-video-processor",
      name: "VP-1000 Series Endoscopic Video Image Processor",
      brand: "concemed",
      category: "endoscopy",
      sub_category: "endoscopy-imaging-systems",
      product_type: "Endoscopic Video Image Processor",
      is_parent_product: true,
      images: [
        "	https://static2.xunxiang.site/uploads/sites/2086/2024/01/d398bc0c944a243ee45596058d0e22f1.jpg",
        "https://concemed-02.obs.cn-north-4.myhuaweicloud.com/f75f484ee2a6f0891fd910db69fcd63f.jpg",
      ],
      description:
        "The VP-1000 Series is an advanced endoscopic video image processor with an integrated multi-spectral LED light source. It delivers high-definition imaging with enhanced mucosal color expression and supports multiple imaging modes for screening, diagnosis, and therapeutic endoscopic procedures.",
      features: [
        "Integrated multi-spectral LED light source",
        "High-definition image processing and display",
        "Enhanced mucosal color expression",
        "Multiple advanced imaging modes",
        "8-inch touch screen control interface",
        "Integrated water delivery system",
        "Compatible with V-1000 series endoscopes",
        "Supports comprehensive endoscopic workflows",
      ],
      variants: ["VP-1000 S", "VP-1000 A", "VP-1000 P"],
      show_image_main: true,
    },
  ],
};

export const companyStats = {
  yearsFounded: 1985,
  partnersCount: partners.length,
  categoriesCount: productCategories.length,
  productsCount: productData.total_products,
  facilitiesServed: "100+",
  support: "24/7",
};

export const contactInfo = {
  companyName:
    "Riyadh International Corporation Medical Equipments & Services, Ltd",
  address: {
    street: "Orouba street, RIC Complex",
    city: "Riyadh",
    zipCode: "2324",
    country: "Kingdom of Saudi Arabia",
    poBox: "P.O. Box 223",
  },
  phone: {
    primary: "+966114654113",
    secondary: "+966114630135",
  },
  email: "info@ric.com.sa",
  workingHours: "Sun - Thu: 8AM - 5PM",
};
