export const productData = {
  total_products: 18,
  products: [
    {
      id: "medispec-em1000-eswl",
      name: "EM1000™ ESWL System",
      brand: "Medispec",
      category: "Capital Equipment",
      sub_category: "Urology – Lithotripsy",
      product_type: "Extracorporeal Shock Wave Lithotripsy (ESWL) System",
      is_parent_product: false,
      images: [
        "https://www.medispec.com/wp-content/uploads/2021/08/EM1000-Title-pic-e1638881167440.png",
        "https://www.medispec.com/wp-content/uploads/2022/08/EM1000-36-Custom.png",
        "https://www.medispec.com/wp-content/uploads/2021/10/stones.png",
      ],
      description:
        "The EM1000™ ESWL System is an advanced electromagnetic lithotripter designed for non-invasive stone management treatment with a high stone-free rate, low re-treatment rate, and outstanding clinical results. Its modular and mobile design fits a wide range of clinical environments without the need for special infrastructure. It offers real-time stone visualization and integrated imaging options.",
      features: [
        "Electromagnetic shockwave technology for efficient stone fragmentation",
        "Highest stone-free rate and lowest re-treatment rate in its class",
        "Modular, mobile design suitable for a variety of clinical settings",
        "Real-time stone visualization during treatment",
        "Versatility for both lithotripsy and endo-urology procedures",
        "Integrated X-ray and ultrasound imaging options",
      ],
      technical_specifications: {
        technology: "Electromagnetic shockwave generation",
        treatment_modes: ["Lithotripsy", "Endo-urology procedures"],
        mobility: "Modular and mobile system",
        integration: "X-ray and optional ultrasound imaging",
        clinical_benefits: [
          "High stone-free rate",
          "Low re-treatment rate",
          "Reduced treatment time",
          "Fits in small clinics to large hospitals",
        ],
      },
      accessories_included: [
        "Control console with automatic stone localization",
        "Motorized treatment table interface",
        "Integrated imaging (Visionspec™) compatibility",
        "Detachable ultrasound probe support",
      ],
      applications: [
        "Renal stone treatment",
        "Ureteric stone treatment",
        "Endo-urology procedures",
      ],
      certifications: [],
      regulatory: {
        fda_classification:
          "Class II – Extracorporeal Shock Wave Lithotripter (21 CFR 876.5990)",
        intended_use:
          "Non-invasive fragmentation of urinary tract stones including kidney and ureter stones",
      },
      distributor: {
        name: "",
        region: "",
        contact: "",
      },
    },
    {
      id: "potent-hp-series",
      name: "Potent HP Series",
      brand: "Potent",
      category: "Urology",
      sub_category: "Laser Systems",
      technology: "Holmium Laser",
      product_type: "Surgical Laser System",
      is_parent_product: true,
      images: [],
      variants: [
        {
          variant_id: "hp-100w",
          name: "HP-100W",
          specifications: {
            max_power_watts: 100,
            pulse_duration_us: "100–1500",
            wavelength_um: 2.1,
          },
        },
        {
          variant_id: "hp-120w",
          name: "HP-120W",
          specifications: {
            max_power_watts: 120,
            pulse_duration_us: "100–1500",
            wavelength_um: 2.1,
          },
        },
        {
          variant_id: "hp-160w",
          name: "HP-160W",
          specifications: {
            max_power_watts: 160,
            pulse_duration_us: "100–1500",
            wavelength_um: 2.1,
          },
        },
      ],
      applications: ["Urology", "Stone Lithotripsy", "Soft Tissue Surgery"],
    },
    {
      id: "potent-hz-series",
      name: "Potent HZ Series",
      brand: "Potent",
      category: "Urology",
      sub_category: "Laser Systems",
      technology: "Holmium Laser",
      product_type: "Surgical Laser System",
      is_parent_product: true,
      images: [],
      variants: [
        {
          variant_id: "hz-50w",
          name: "HZ-50W",
          specifications: {
            max_power_watts: 50,
            wavelength_um: 2.1,
          },
        },
        {
          variant_id: "hz-60w",
          name: "HZ-60W",
          specifications: {
            max_power_watts: 60,
            wavelength_um: 2.1,
          },
        },
        {
          variant_id: "hz-80w",
          name: "HZ-80W",
          specifications: {
            max_power_watts: 80,
            wavelength_um: 2.1,
          },
        },
        {
          variant_id: "hz-90w",
          name: "HZ-90W",
          specifications: {
            max_power_watts: 90,
            wavelength_um: 2.1,
          },
        },
      ],
      applications: ["Urology", "ENT", "General Surgery"],
    },
    {
      id: "potent-pulsed-master",
      name: "Pulsed Master",
      brand: "Potent",
      category: "Urology",
      sub_category: "Laser Systems",
      technology: "Thulium Fiber Laser",
      product_type: "Laser System",
      is_parent_product: false,
      variants: [],
      images: [],
      applications: [
        "Kidney stones",
        "BPH treatment",
        "Soft tissue surgery",
        "Urology procedures",
      ],
    },
    {
      id: "medispec-single-use-flexible-ureterorenoscope",
      name: "Single-Use Video Flexible Ureterorenoscope",
      brand: "Medispec",
      category: "Urology",
      sub_category: "Endoscopic Imaging",
      technology: "Single-Use Endoscopic Imaging",
      product_type: "Flexible Ureterorenoscope",
      is_parent_product: false,
      variants: [],
      images: [],
      model: "RP-U-C0305",
      optical_system: {
        field_of_view: "120°",
        depth_of_field: "5mm–50mm",
        direction_of_view: "0°",
      },
      insertion_portion: {
        outer_diameter: "2.5mm (7.5Fr)",
        inner_diameter: "3.6Fr",
        working_length: "670mm",
      },
      applications: [
        "Ureteroscopy",
        "Kidney stone management",
        "Urological diagnostics",
      ],
      regulatory: {
        authorization_number: "MDMA-2-2023-2396",
      },
      distributor: {
        name: "Riyadh International Corporation",
        region: "Saudi Arabia",
      },
    },
    {
      id: "combat-brs-system",
      name: "COMBAT BRS",
      full_name:
        "Combined Antineoplastic Thermotherapy Bladder Recirculation System",
      brand: "COMBAT Medical",
      category: "Cancer Treatment",
      sub_category: "Bladder Cancer Treatment",
      technology: "Intravesical Chemotherapy with Hyperthermia",
      product_type: "Bladder Recirculation System",
      is_parent_product: false,
      variants: [],
      images: [],
      description:
        "The COMBAT BRS is an innovative thermotherapy bladder recirculation system designed to deliver hyperthermic intravesical chemotherapy (HIVEC®) for the treatment of non-muscle invasive bladder cancer (NMIBC).",
      clinical_indications: [
        "Non-muscle invasive bladder cancer (NMIBC)",
        "Adjunct intravesical chemotherapy",
      ],
      key_benefits: [
        "Improved efficacy of intravesical chemotherapy through hyperthermia",
        "Uniform drug distribution within the bladder",
        "Portable and easy to integrate into existing clinical workflows",
        "Reduced recurrence and progression rates",
      ],
      system_components: [
        "Touchscreen control unit",
        "Peristaltic pump",
        "Aluminium foil heat exchanger",
        "Pressure sensor and tube detection",
        "Temperature probe port",
        "Disposable catheter set (16F, 3-way, coude tip)",
      ],
      functional_features: {
        temperature_control: "Continuous delivery at 40–44°C (±1°C)",
        recirculation: "Accurate and continuous fluid recirculation",
        monitoring: "Real-time temperature and pressure monitoring",
        data_storage: "USB export (CSV / TXT formats)",
      },
      safety_features: [
        "High and low temperature alarms",
        "High pressure alarm",
        "Automatic safety cut-off",
        "End-of-treatment alarm and auto-stop",
        "Audible and visual alerts",
      ],
      technical_specifications: {
        dimensions_mm: {
          height: 400,
          width: 250,
          depth: 255,
        },
        weight_kg: "9.6 (plus portable stand)",
        electrical_classification: "Class II, Type B",
        ingress_protection: "IPX2",
        function_mode: "Continuous delivery at set temperature",
        certifications: [
          "UL 60601-1",
          "IEC 60601-1",
          "IEC 60601-2",
          "EN 55011",
          "CAN/CSA-C22.2",
          "CE 0120",
        ],
      },
      clinical_evidence: {
        usage_history: "In clinical use since 2011",
        notes:
          "Demonstrated improved outcomes and comparable tolerability to MMC at room temperature",
      },
      regulatory: {
        authorization_number: "MDMA 1-2017-2052",
      },
      distributor: {
        name: "Riyadh International Corporation for Medical Equipment & Services",
        region: "Kingdom of Saudi Arabia",
        contact_email: "ricmede@ricmedical.com.sa",
      },
      manufacturer_website: "https://www.combat-medical.com",
    },
    {
      id: "basda-bstar-150-mri",
      name: "Bstar-150",
      brand: "BASDA",
      category: "Medical Imaging",
      sub_category: "MRI Systems",
      technology: "Magnetic Resonance Imaging (MRI)",
      product_type: "Superconducting MRI System",
      is_parent_product: false,
      variants: [],
      images: [],
      description:
        "Bstar-150 is a 1.5T superconducting MRI system developed by BASDA, designed to deliver high image quality, patient comfort, and efficient clinical workflow for advanced diagnostic imaging.",
      manufacturer_background: {
        founded_year: 2000,
        headquarters: "Shenzhen, Guangdong, China",
        profile:
          "High-tech company focused on R&D, production, and service of medical imaging and radiotherapy devices",
      },
      key_features: [
        "1.5T superconducting magnet",
        "Golden-ratio magnet design for patient comfort and homogeneity balance",
        "Dual-side operation panel for improved workflow",
        "Smart gantry-mounted control screen",
        "High-accuracy diagnosis with intelligent speed control",
        "Motor-driven patient table with high positioning accuracy",
      ],
      magnet_system: {
        type: "Superconductive",
        field_strength_tesla: 1.5,
        shielding_method: "Active",
        shimming: "Active + Passive + Dynamic",
        magnet_stability: "≤0.1 ppm/h",
        inner_diameter_mm: 600,
        magnet_length_mm: 1570,
        liquid_helium_capacity_liters: 800,
      },
      gradient_system: {
        max_gradient_strength: "41 mT/m",
        max_slew_rate: "187 T/m/s",
        min_rise_time_ms: 0.22,
        cooling_system: "Water cooling",
      },
      rf_system: {
        rf_amplifier_power_kw: 18,
        center_frequency: "63.87 MHz",
        rf_channels: 16,
        ad_converters: 16,
        receiver_bandwidth: "≥1.0 MHz",
        signal_resolution_bits: 16,
        noise_level_db: "≤0.45 dB",
      },
      computer_system: {
        software: "BASDA MRI Software",
        monitor_size_inch: 24,
        resolution: "1920×1200",
        storage: ["DVD", "USB"],
        dicom_support: "DICOM 3.0",
      },
      patient_table: {
        horizontal_movement_range_mm: 2055,
        max_speed_mm_per_s: 220,
        lowest_height_mm: 675,
        max_load_kg: 200,
        position_accuracy_mm: 0.5,
        table_length_mm: 2400,
      },
      imaging_capabilities: {
        sequences: [
          "SE 2D/3D",
          "FSE 2D/3D",
          "GRE 2D/3D",
          "DWI",
          "IR",
          "FLAIR",
          "STIR",
        ],
        advanced_techniques: [
          "MR Angiography (MRA)",
          "MR Cholangiopancreatography (MRCP)",
          "Diffusion Tensor Imaging (DTI)",
          "SWI",
          "Parallel imaging",
          "Automatic calibration",
          "Motion correction",
          "Respiratory compensation",
        ],
        max_b_value: 10000,
        min_slice_thickness_mm: 0.1,
        min_3d_thickness_mm: 0.05,
        max_fov_cm: 50,
        min_fov_cm: 1,
      },
      scan_environment: {
        table_drive: "Motor-driven",
      },
      certifications: [],
      regulatory: {
        authorization_number: "GHTF-2021-0692",
      },
      distributor: {
        name: "Riyadh International Corporation for Medical Equipment & Services",
        region: "Kingdom of Saudi Arabia",
        contact_email: "ricmede@ricmedical.com.sa",
      },
    },
    // Allwin Medical Devices Products
    {
      id: "allsoft-ureteral-stents-open-closed-intraoperative",
      name: "allSoft Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
      brand: "Allwin Medical Devices",
      category: "Disposables",
      sub_category: "Ureteral Stents",
      product_type: "Disposable Ureteral Stent",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Open-Tip-13.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Open-Tip-14-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Closed-Tip-13-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Ureteral-Stents-Closed-Tip-12-600x600.jpg",
      ],
      description:
        "The allSoft Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopacity for accurate positioning, and centimeter markings for precise placement.",
      features: [
        "Low encrustation tendency to facilitate easy removal of the stent",
        "Soft polyurethane material ensures high patient comfort",
        "Wide lumen for superior drainage",
        "Radiopaque stent to enable accurate positioning",
        "Centimeter marking to aid in stent advancement and precise placement",
      ],
      variants: [
        "SOT4.7/16 | SS4.7/16 | SSI4.7/16",
        "SOT4.7/24 | SS4.7/24 | SSI4.7/24",
        "SOT4.7/26 | SS4.7/26 | SSI4.7/26",
        "SOT4.7/28 | SS4.7/28 | SSI4.7/28",
        "SOT4.7/30 | SS4.7/30 | SSI4.7/30",
        "SOT5/16 | SS5/16 | SSI5/16",
        "SOT5/24 | SS5/24 | SSI5/24",
        "SOT5/26 | SS5/26 | SSI5/26",
        "SOT5/28 | SS5/28 | SSI5/28",
        "SOT5/30 | SS5/30 | SSI5/30",
        "SOT6/16 | SS6/16 | SSI6/16",
        "SOT6/24 | SS6/24 | SSI6/24",
        "SOT6/26 | SS6/26 | SSI6/26",
        "SOT6/28 | SS6/28 | SSI6/28",
        "SOT6/30 | SS6/30 | SSI6/30",
        "SOT7/16 | SS7/16 | SSI7/16",
        "SOT7/24 | SS7/24 | SSI7/24",
        "SOT7/26 | SS7/26 | SSI7/26",
        "SOT7/28 | SS7/28 | SSI7/28",
        "SOT7/30 | SS7/30 | SSI7/30",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "r-plus-ureteral-stents-open-closed-intraoperative",
      name: "R+ Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
      brand: "Allwin Medical Devices",
      category: "Disposables",
      sub_category: "Ureteral Stents",
      product_type: "Disposable Ureteral Stent",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-16.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-16.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-17.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-14-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-13-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/R-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
      ],
      description:
        "The R+ Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopaque stent for accurate positioning, centre marking for precise placement, and a long pusher for use via ureteroscope.",
      features: [
        "Low encrustation tendency to facilitate easy removal of the stent",
        "Soft polyurethane material ensures high patient comfort",
        "Wide lumen for superior drainage",
        "Radiopaque stent to enable accurate positioning",
        "Centimetre marking to aid in stent advancement and precise placement",
        "4.7 Fr stent with a long pusher for ureteroscope use",
      ],
      variants: [
        "SOT4.7/16-R+ | SS4.7/16-R+ | SSI4.7/16-R+",
        "SOT4.7/24-R+ | SS4.7/24-R+ | SSI4.7/24-R+",
        "SOT4.7/26-R+ | SS4.7/26-R+ | SSI4.7/26-R+",
        "SOT4.7/28-R+ | SS4.7/28-R+ | SSI4.7/28-R+",
        "SOT4.7/30-R+ | SS4.7/30-R+ | SSI4.7/30-R+",
        "SOT5/16-R+ | SS5/16-R+ | SSI5/16-R+",
        "SOT5/24-R+ | SS5/24-R+ | SSI5/24-R+",
        "SOT5/26-R+ | SS5/26-R+ | SSI5/26-R+",
        "SOT5/28-R+ | SS5/28-R+ | SSI5/28-R+",
        "SOT5/30-R+ | SS5/30-R+ | SSI5/30-R+",
        "SOT6/16-R+ | SS6/16-R+ | SSI6/16-R+",
        "SOT6/24-R+ | SS6/24-R+ | SSI6/24-R+",
        "SOT6/26-R+ | SS6/26-R+ | SSI6/26-R+",
        "SOT6/28-R+ | SS6/28-R+ | SSI6/28-R+",
        "SOT6/30-R+ | SS6/30-R+ | SSI6/30-R+",
        "SOT7/16-R+ | SS7/16-R+ | SSI7/16-R+",
        "SOT7/24-R+ | SS7/24-R+ | SSI7/24-R+",
        "SOT7/26-R+ | SS7/26-R+ | SSI7/26-R+",
        "SOT7/28-R+ | SS7/28-R+ | SSI7/28-R+",
        "SOT7/30-R+ | SS7/30-R+ | SSI7/30-R+",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "r-plus-ureteral-stents-open-closed-intraoperative",
      name: "R+ Ureteral Stents (Open Tip, Closed Tip & Intraoperative)",
      brand: "Allwin Medical Devices",
      category: "Disposables",
      sub_category: "Ureteral Stents",
      product_type: "Disposable Ureteral Stent",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/RRenal-Transplant-Stent-Open-Tip-14.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Open-Tip-18-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RRenal-Transplant-Stent-Closed-Tip-15-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/RUreteral-Stents-Closed-Tip-15-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/R-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
      ],
      description:
        "The R+ Ureteral Stents are intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. They feature low encrustation tendency, soft polyurethane material for high patient comfort, wide lumen for superior drainage, radiopaque stent for accurate positioning, centre marking for precise placement, and a long pusher for use via ureteroscope.",
      features: [
        "Low encrustation tendency to facilitate easy removal of the stent",
        "Soft polyurethane material ensures high patient comfort",
        "Wide lumen for superior drainage",
        "Radiopaque stent to enable accurate positioning",
        "Centimetre marking to aid in stent advancement and precise placement",
        "4.7 Fr stent with a long pusher for ureteroscope use",
      ],
      variants: [
        "SOT4.7/16-R+ | SS4.7/16-R+ | SSI4.7/16-R+",
        "SOT4.7/24-R+ | SS4.7/24-R+ | SSI4.7/24-R+",
        "SOT4.7/26-R+ | SS4.7/26-R+ | SSI4.7/26-R+",
        "SOT4.7/28-R+ | SS4.7/28-R+ | SSI4.7/28-R+",
        "SOT4.7/30-R+ | SS4.7/30-R+ | SSI4.7/30-R+",
        "SOT5/16-R+ | SS5/16-R+ | SSI5/16-R+",
        "SOT5/24-R+ | SS5/24-R+ | SSI5/24-R+",
        "SOT5/26-R+ | SS5/26-R+ | SSI5/26-R+",
        "SOT5/28-R+ | SS5/28-R+ | SSI5/28-R+",
        "SOT5/30-R+ | SS5/30-R+ | SSI5/30-R+",
        "SOT6/16-R+ | SS6/16-R+ | SSI6/16-R+",
        "SOT6/24-R+ | SS6/24-R+ | SSI6/24-R+",
        "SOT6/26-R+ | SS6/26-R+ | SSI6/26-R+",
        "SOT6/28-R+ | SS6/28-R+ | SSI6/28-R+",
        "SOT6/30-R+ | SS6/30-R+ | SSI6/30-R+",
        "SOT7/16-R+ | SS7/16-R+ | SSI7/16-R+",
        "SOT7/24-R+ | SS7/24-R+ | SSI7/24-R+",
        "SOT7/26-R+ | SS7/26-R+ | SSI7/26-R+",
        "SOT7/28-R+ | SS7/28-R+ | SSI7/28-R+",
        "SOT7/30-R+ | SS7/30-R+ | SSI7/30-R+",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "allsoft-renal-transplant-stent-open-closed-tip",
      name: "allSoft Renal Transplant Stent (Open Tip & Closed Tip)",
      brand: "Allwin Medical Devices",
      category: "Disposables",
      sub_category: "Renal Transplant Stents",
      product_type: "Disposable Renal Transplant Stent",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-3.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Closed-Tip-9-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Open-Tip-12-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Renal-Transplant-Stent-Open-Tip-Closed-Tip.png",
      ],
      description:
        "The allSoft Renal Transplant Stent is intended to temporarily facilitate the drainage of urine from kidney to bladder by a trained physician. It is made of soft, biocompatible polyurethane with low encrustation tendency and is sized to fit renal transplant needs. Radiopaque markings aid precise placement. Suitable for use in transplant-related urinary drainage procedures.",
      features: [
        "Soft polyurethane material for high patient comfort",
        "Low encrustation tendency to facilitate easy removal",
        "Biocompatible material",
        "Sized for renal transplant-specific anatomy",
        "Radiopaque centremark for precise placement",
      ],
      variants: [
        "RTS-O6/12 | RTS-C6/12",
        "RTS-O6/14 | RTS-C6/14",
        "RTS-O6/16 | RTS-C6/16",
        "RTS-O7/12 | RTS-C7/12",
        "RTS-O7/14 | RTS-C7/14",
        "RTS-O7/16 | RTS-C7/16",
        "RTS-O8/12 | RTS-C8/12",
        "RTS-O8/14 | RTS-C8/14",
        "RTS-O8/16 | RTS-C8/16",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
    {
      id: "allsoft-multiloop-ureteral-stents-open-closed-tip",
      name: "allSoft Multiloop Ureteral Stents (Open Tip & Closed Tip)",
      brand: "Allwin Medical Devices",
      category: "Disposables",
      sub_category: "Ureteral Stents",
      product_type: "Disposable Ureteral Stent",
      is_parent_product: false,
      images: [
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Open-Tip-9.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Bladder-end-Multiloop-6-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Both-side-Multiloop-5-600x600.jpg",
        "https://allwinmedical.com/wp-content/uploads/2020/11/allSoft-Multiloop-Ureteral-Stents-Closed-Tip-7-600x600.jpg",
      ],
      description:
        "The allSoft Multiloop Ureteral Stent is intended to temporarily facilitate drainage of urine from kidney to bladder by a trained physician. It offers both open and closed tip options for bladder-end or both-end multiloop configurations and is universally suitable for ureteral lengths from 22 cm to 30 cm.",
      features: [
        "Available in open and closed tip configurations",
        "Multiloop design at bladder end or both ends for improved anchorage",
        "Suitable for ureter lengths 22–30 cm",
        "Soft polyurethane for patient comfort",
        "Radiopaque marking for accurate positioning",
      ],
      variants: [
        "SOT4.7/ML | SS4.7/ML | SOT4.7/ML-ML | SS4.7/ML-ML",
        "SOT5/ML | SS5/ML | SOT5/ML-ML | SS5/ML-ML",
        "SOT6/ML | SS6/ML | SOT6/ML-ML | SS6/ML-ML",
        "SOT7/ML | SS7/ML | SOT7/ML-ML | SS7/ML-ML",
      ],
      combinations: {
        with_guidewire: "Add suffix - G",
        with_suture: "Add suffix - S",
        with_clamp: "Add suffix - C",
        with_hydrophilic_coating: "Add suffix - H",
      },
    },
  ],
};

const backup = [
  {
    id: "allwin-ureteral-stents",
    name: "Ureteral Stents",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Ureteral Stents",
    product_type: "Disposable Implant",
    images: [],
    variants: [
      "allSoft Ureteral Stents",
      "R+ Ureteral Stents",
      "Renal Transplant Stents",
      "Multiloop Ureteral Stents",
      "Pediatric Ureteral Stents",
      "Carbothane Ureteral Stents",
    ],
  },
  {
    id: "allwin-speciality-stents",
    name: "Speciality Ureteral Stents",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Speciality Stents",
    product_type: "Disposable Implant",
    images: [],
    variants: [
      "Tumor Stents",
      "Endopyelotomy Stents",
      "Urinary Diversion Stents (Mono-J)",
    ],
  },
  {
    id: "allwin-stent-removers",
    name: "Stent Removal Devices",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Stent Accessories",
    product_type: "Disposable / Reusable Instrument",
    images: [],
    variants: ["Pull-it Stent Remover", "Captura Stent Remover Snare"],
  },
  {
    id: "allwin-nephrostomy-sets",
    name: "Percutaneous Nephrostomy Sets",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Nephrostomy",
    product_type: "Disposable Drainage Device",
    images: [],
    variants: [
      "allDrain Nephrostomy Drainage Set – Pigtail",
      "Ultima Nephrostomy Drainage Set",
      "Malecot Nephrostomy Set",
      "Re-Entry Malecot Catheter",
    ],
  },
  {
    id: "allwin-suprapubic-sets",
    name: "Suprapubic Puncture Sets",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Suprapubic Access",
    product_type: "Disposable Access Device",
    images: [],
    variants: [
      "UltraDrain Suprapubic Puncture Set",
      "Spear Suprapubic Metal Tip Puncture Set",
    ],
  },
  {
    id: "allwin-balloon-dilators",
    name: "Balloon Dilators",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Dilatation",
    product_type: "Disposable Dilatation Device",
    images: [],
    variants: [
      "TU-Track Transureteroscopic Balloon Dilator",
      "UreTrack Ureteral Balloon Dilator",
      "NephroTrack Nephrostomy Track Balloon Dilator",
    ],
  },
  {
    id: "allwin-dilators",
    name: "Ureteral & Renal Dilators",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Dilatation",
    product_type: "Disposable Dilator",
    images: [],
    variants: [
      "ARMADA Ureteral Dilators",
      "Fascial Dilators",
      "ARMADA Nottingham One Step Dilator",
      "Amplatz Renal Dilator Set",
      "Amplatz Sheath",
      "Introducer Sheath",
      "Introducer Catheter",
      "Meatal Dilator (Adult & Pediatric)",
    ],
  },
  {
    id: "allwin-guidewires-needles",
    name: "Guidewires & Needles",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Access Devices",
    product_type: "Disposable Access Device",
    images: [],
    variants: [
      "FlexiGuide J-Tip Guidewire",
      "Cobra Nitinol Guidewire",
      "Initial Puncture Needle",
      "Trocar Tip Needle",
      "Chiba Needle",
      "Injection Needle (Plastic)",
      "Injection Needle (Metallic)",
    ],
  },
  {
    id: "allwin-irrigation-devices",
    name: "Irrigation & Evacuation Devices",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Irrigation",
    product_type: "Reusable / Disposable Device",
    images: [],
    variants: [
      "TUR-VAC Bladder Evacuator",
      "Ellick Bladder Evacuator",
      "Asepto Bulb Irrigation Syringe",
      "Toomey Syringe",
      "Trackfinder Bulb Irrigator",
      "Urine Bag Connector",
    ],
  },
  {
    id: "allwin-incontinence-device",
    name: "Male Incontinence Clamp",
    brand: "Allwin Medical Devices",
    category: "Disposables",
    sub_category: "Incontinence",
    product_type: "External Device",
    images: [],
    variants: ["Contistrap™ Male Incontinence Clamp"],
  },
];
